Fix some clang warnings and general cleanups
eepp/babeltrace pull request #14
Opened 2018-12-18 21:46 UTC by frdeso

2018-12-18 23:13 UTC, eepp commented
Almost okay:

1. Can you rebase on the tip of my branch? The only thing to change should be something about `BT_MESSAGE_ITERATOR_STATUS_CANCELED` in `muxer.c`.
2. 8c6987c02ce1baf06d38f7193ecd91e80ce29def: please name the referred patch instead of using the commit ID because it could change in the future as this whole branch is not merged into `master` yet.
3. 14db54fc2575df34fa021bbf093e8a5ef558b3e5: commit message: put `()` after function name.
4. a452d8c91695cace892280cdd34598bbd0248902: commit message: prefix with `ctf plugin:`.

2018-12-18 23:15 UTC, eepp requested changes
Almost okay:

1. Can you rebase on the tip of my branch? The only thing to change should be something about `BT_MESSAGE_ITERATOR_STATUS_CANCELED` in `muxer.c`.
2. 8c6987c02ce1baf06d38f7193ecd91e80ce29def: please name the referred patch instead of using the commit ID because it could change in the future as this whole branch is not merged into `master` yet.
3. 14db54fc2575df34fa021bbf093e8a5ef558b3e5: commit message: put `()` after function name.
4. a452d8c91695cace892280cdd34598bbd0248902: commit message: use `Fix: ctf plugin:` prefix.

2018-12-18 23:15 UTC, eepp commented on lib/graph/query-executor.c
> +		exec_status = BT_QUERY_EXECUTOR_STATUS_CANCELED;
Good catch!

2018-12-18 23:15 UTC, eepp commented on plugins/ctf/common/metadata/visitor-generate-ir.c
> -			stream_class = stream_class;
Wow... :100:

2018-12-19 04:17 UTC, frdeso commented
I made the requested changes.

2018-12-20 14:01 UTC, merged