Adapt `src.ctf.lttng-live` to current API
eepp/babeltrace pull request #19
Opened 2019-03-26 01:54 UTC by frdeso

A `src.ctf.lttng-live` component now ensures the monotonic ordering of
the timestamps its outgoing messages. The component can receive messages
from multiples viewer session (UST 64bit, UST 32bit and/or Kernel) that
in turn may contain one or more traces that in turn may contain one or
more streams of messages. Messages from all these streams have to be
ordered into a single flow of messages where every message has a
timestamp equal or larger than the previous one.. This muxing is done by
tracking the next message of each of the live stream iterator and
returning the message with the smallest timestamp.

Parameters
=========
The `url` string parameter controls the URL of the LTTng Relay Daemon to
which the `src.ctf.lttng-live` should register to received traces.

The `retry` boolean parameter controls whether the component should keep
trying to connect to the LTTng relay daemon even if the requested
session name configured on the host. By default, it's set to False and
thus the message iterator will return a END status down the graph.

Future improvement
===============
Using a priority queue to order the messages would speed up the muxing
of messages.

Known limitation
=============
If a new live stream iterator returns a message that has a timestamp
smaller (that happened before) than the last message forwarded
downstream but the `src.ctf.lttng-live` message iterator. The message
iterator will return with an error status. I am not sure if this
situation can happen in a single host configuration (which is the only
supported configuration).

Signed-off-by: Francis Deslauriers <francis.deslauriers@efficios.com>

2019-03-26 01:56 UTC, frdeso commented
I am opened to suggestion of a different name for the `retry` parameter.

2019-03-26 15:48 UTC, frdeso commented
I am currently trying to confirm that inactivity messages are create correctly.

2019-03-26 16:06 UTC, frdeso commented on plugins/ctf/lttng-live/lttng-live.c
> +			(uint64_t) lttng_live_stream->current_inactivity_ts);
This cast bothers me.

2019-03-27 01:39 UTC, frdeso commented
Rebased on current optimalize branch

2019-04-01 14:52 UTC, frdeso commented
I added a commit to fix an error propagation bug in the bt_graph_configue() function.

2019-04-18 18:57 UTC, eepp requested changes
General to all files:

* Use `bool` instead of `bt_bool` (internally).
* Indent a continuation with a single tab, not two.

> Reviewed 13 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eepp/babeltrace/19#-:-Lclmwb_13E5w4s938yp:bcxy9jd)* status: all files reviewed, 47 unresolved discussions (waiting on @frdeso)

___
*[plugins/ctf/Makefile.am, line 3 at r1](https://reviewable.io/reviews/eepp/babeltrace/19#-LclIyhl6U0USdbCl6PE:-LclIyhl6U0USdbCl6PF:b5s9jxj) ([raw file](https://github.com/eepp/babeltrace/blob/8d954d21f0d27252bf4a90dbd7e4d408a594cd1f/plugins/ctf/Makefile.am#L3)):*
> ```Makefile
> SUBDIRS = common \
> 	fs-src \
> 	fs-sink \
> ```

It's back! :smiley: 
___
*[plugins/ctf/plugin.c, line 40 at r1](https://reviewable.io/reviews/eepp/babeltrace/19#-LclMQvJClZw2Qpdhu8h:-LclMQvJClZw2Qpdhu8i:bckpflu) ([raw file](https://github.com/eepp/babeltrace/blob/8d954d21f0d27252bf4a90dbd7e4d408a594cd1f/plugins/ctf/plugin.c#L40)):*
> ```C
> 
> /* Initialize plug-in description. */
> BT_PLUGIN("ctf");
> ```

Use an identifier, not a C string.
___
*[plugins/ctf/lttng-live/data-stream.c, line 78 at r1](https://reviewable.io/reviews/eepp/babeltrace/19#-LclJIby8xE_4FsF3X4W:-LclJIby8xE_4FsF3X4X:b2j5ld8) ([raw file](https://github.com/eepp/babeltrace/blob/8d954d21f0d27252bf4a90dbd7e4d408a594cd1f/plugins/ctf/lttng-live/data-stream.c#L78)):*
> ```C
> static
> bt_stream *medop_borrow_stream(bt_stream_class *stream_class,
> 		int64_t stream_id, void *data)
> ```

`bt_stream_create_with_id()` accepts an unsigned ID.

`stream_id` is signed here because it is possible that the stream's packet header did not contain any stream ID. Or is it?

Consider that `stream_id` can be negative. If the LTTng live protocol makes this impossible (stream ID always exists), then check this in the metadata once at some other location and `BT_ASSERT()` here that it's the case, or return an error here if `stream_id` is negative. Otherwise you need to find an unused ID for the call to `bt_stream_create()`.
___
*[plugins/ctf/lttng-live/data-stream.c, line 93 at r1](https://reviewable.io/reviews/eepp/babeltrace/19#-LclN1sR6mbyxC-v6bw9:-LclN1sR6mbyxC-v6bwA:bb83yo3) ([raw file](https://github.com/eepp/babeltrace/blob/8d954d21f0d27252bf4a90dbd7e4d408a594cd1f/plugins/ctf/lttng-live/data-stream.c#L93)):*
> ```C
> 			/* No stream ID */
> 			lttng_live_stream->stream = bt_stream_create(
> 					stream_class,
> ```

Single tab to indent continuation (check other locations too).
___
*[plugins/ctf/lttng-live/lttng-live.h, line 67 at r1](https://reviewable.io/reviews/eepp/babeltrace/19#-LclO2k8E3u3qJdo1NB4:-LclO2k8E3u3qJdo1NB5:b-ye3nbi) ([raw file](https://github.com/eepp/babeltrace/blob/8d954d21f0d27252bf4a90dbd7e4d408a594cd1f/plugins/ctf/lttng-live/lttng-live.h#L67)):*
> ```objc
> /* Iterator over a live stream. */
> struct lttng_live_stream_iterator {
> 	bt_stream *stream;
> ```

Please, for everything that is shared as `stream`, add a comment at the top of the member to indicate if it's weak or "owned by this".
___
*[plugins/ctf/lttng-live/lttng-live.h, line 84 at r1](https://reviewable.io/reviews/eepp/babeltrace/19#-LclNhkyAgbJ2FoxAyVF:-LclNhkyAgbJ2FoxAyVG:bt7jh18) ([raw file](https://github.com/eepp/babeltrace/blob/8d954d21f0d27252bf4a90dbd7e4d408a594cd1f/plugins/ctf/lttng-live/lttng-live.h#L84)):*
> ```objc
> 
> 	uint64_t last_inactivity_msg_ts;
> 	uint64_t current_inactivity_ts;
> ```

Are those clock snapshot values (I believe they should?), or timestamps in nanoseconds? Comment.
___
*[plugins/ctf/lttng-live/lttng-live.h, line 88 at r1](https://reviewable.io/reviews/eepp/babeltrace/19#-LclNnIv2gjQZqMNayyv:-LclNnIv2gjQZqMNayyw:b-jqdhbd) ([raw file](https://github.com/eepp/babeltrace/blob/8d954d21f0d27252bf4a90dbd7e4d408a594cd1f/plugins/ctf/lttng-live/lttng-live.h#L88)):*
> ```objc
> 	enum lttng_live_stream_state state;
> 
> 	bt_message *current_msg;
> ```

Owned by this? Comment.
___
*[plugins/ctf/lttng-live/lttng-live.h, line 89 at r1](https://reviewable.io/reviews/eepp/babeltrace/19#-LclNqq71Cgp6YxbofVX:-LclNqq71Cgp6YxbofVY:b-pismjs) ([raw file](https://github.com/eepp/babeltrace/blob/8d954d21f0d27252bf4a90dbd7e4d408a594cd1f/plugins/ctf/lttng-live/lttng-live.h#L89)):*
> ```objc
> 
> 	bt_message *current_msg;
> 	int64_t current_msg_ts;
> ```

CS value or ns? Comment.
___
*[plugins/ctf/lttng-live/lttng-live.h, line 118 at r1](https://reviewable.io/reviews/eepp/babeltrace/19#-LclOIC1C9aezBo5AzIW:-LclOIC1C9aezBo5AzIX:b-7ht83q) ([raw file](https://github.com/eepp/babeltrace/blob/8d954d21f0d27252bf4a90dbd7e4d408a594cd1f/plugins/ctf/lttng-live/lttng-live.h#L118)):*
> ```objc
> 	GPtrArray *stream_iterators;
> 
> 	bt_bool new_metadata_needed;
> ```

Use `bool`.
___
*[plugins/ctf/lttng-live/lttng-live.h, line 135 at r1](https://reviewable.io/reviews/eepp/babeltrace/19#-LclOOCN-F2H8tnP8we_:-LclOOCN-F2H8tnP8wea:b35n0n0) ([raw file](https://github.com/eepp/babeltrace/blob/8d954d21f0d27252bf4a90dbd7e4d408a594cd1f/plugins/ctf/lttng-live/lttng-live.h#L135)):*
> ```objc
> 	bt_bool new_streams_needed;
> 	bt_bool lazy_stream_msg_init;
> 	bt_bool closed;
> ```

`bool` for all those.
___
*[plugins/ctf/lttng-live/lttng-live.h, line 151 at r1](https://reviewable.io/reviews/eepp/babeltrace/19#-LclOiIp3349rQU-MqWA:-LclOiIp3349rQU-MqWB:b-rz00id) ([raw file](https://github.com/eepp/babeltrace/blob/8d954d21f0d27252bf4a90dbd7e4d408a594cd1f/plugins/ctf/lttng-live/lttng-live.h#L151)):*
> ```objc
> 	size_t max_query_size;
> 
> 	bt_bool has_msg_iter;
> ```

Please comment about this.
___
*[plugins/ctf/lttng-live/lttng-live.h, line 154 at r1](https://reviewable.io/reviews/eepp/babeltrace/19#-LclOp96-nXGZ65b2XPv:-LclOp96-nXGZ65b2XPw:biediwy) ([raw file](https://github.com/eepp/babeltrace/blob/8d954d21f0d27252bf4a90dbd7e4d408a594cd1f/plugins/ctf/lttng-live/lttng-live.h#L154)):*
> ```objc
> };
> 
> struct lttng_live_msg_iter {
> ```

Comment about the ownership of each pointer member.
___
*[plugins/ctf/lttng-live/lttng-live.c, line 130 at r1](https://reviewable.io/reviews/eepp/babeltrace/19#-LclJf6-8xEFFJP0Marr:-LclJf6-8xEFFJP0Mars:bazpyks) ([raw file](https://github.com/eepp/babeltrace/blob/8d954d21f0d27252bf4a90dbd7e4d408a594cd1f/plugins/ctf/lttng-live/lttng-live.c#L130)):*
> ```C
> 			g_ptr_array_index(session->traces, trace_idx);
> 		if (trace->id == trace_id) {
> 			return trace;
> ```

Can we have a single return point (`end` label, etc.) for this one?
___
*[plugins/ctf/lttng-live/lttng-live.c, line 139 at r1](https://reviewable.io/reviews/eepp/babeltrace/19#-LclQANdACCymO1BrgNq:-LclQANdACCymO1BrgNr:b-ebxdxi) ([raw file](https://github.com/eepp/babeltrace/blob/8d954d21f0d27252bf4a90dbd7e4d408a594cd1f/plugins/ctf/lttng-live/lttng-live.c#L139)):*
> ```C
> void lttng_live_destroy_trace(struct lttng_live_trace *trace)
> {
> 	BT_LOGI("Destroy lttng_live_trace");
> ```

Use `BT_LOGD()`.
___
*[plugins/ctf/lttng-live/lttng-live.c, line 147 at r1](https://reviewable.io/reviews/eepp/babeltrace/19#-LclQR8I-Q5DFgHNJPEC:-LclQR8I-Q5DFgHNJPED:b-7em96f) ([raw file](https://github.com/eepp/babeltrace/blob/8d954d21f0d27252bf4a90dbd7e4d408a594cd1f/plugins/ctf/lttng-live/lttng-live.c#L147)):*
> ```C
> 		BT_TRACE_PUT_REF_AND_RESET(trace->trace);
> 	}
> 	if (trace->trace_class) {
> ```

The "put ref and reset" macros check for `NULL`, so you don't need to check it again here. Same thing for `trace->trace` above.
___
*[plugins/ctf/lttng-live/lttng-live.c, line 190 at r1](https://reviewable.io/reviews/eepp/babeltrace/19#-LclQkOME5trXLVeAYr4:-LclQkOME5trXLVeAYr5:b-k8k6g0) ([raw file](https://github.com/eepp/babeltrace/blob/8d954d21f0d27252bf4a90dbd7e4d408a594cd1f/plugins/ctf/lttng-live/lttng-live.c#L190)):*
> ```C
> 	trace = lttng_live_find_trace(session, trace_id);
> 	if (trace) {
> 		return trace;
> ```

Please use single return point.
___
*[plugins/ctf/lttng-live/lttng-live.c, line 215 at r1](https://reviewable.io/reviews/eepp/babeltrace/19#-LclQqgv48rrGV9W2a0o:-LclQqgv48rrGV9W2a0p:bg6a4p7) ([raw file](https://github.com/eepp/babel [...]

2019-04-18 21:48 UTC, eepp reviewed
Just making this review to close r2 as it was the result of a rebase on the modified base.

> *[Reviewable](https://reviewable.io/reviews/eepp/babeltrace/19#-:-LcmPmDD-A843KhIOPFc:b-4dvoph)* status: all files reviewed, 47 unresolved discussions (waiting on @frdeso)



<!-- Sent from Reviewable.io -->

2019-04-19 02:30 UTC, eepp reviewed
I have another question.

> The `retry` boolean parameter controls whether the component should keep trying to connect to the LTTng relay daemon even if the requested session name is not currently configured on the host. By default, it's set to False and thus the message iterator will return a END status down the graph if the session name is not found.

Should the message iterator be ended in this case, or instead should the component or the message iterator simply fail to initialize? Having an ended message iterator makes it look like there was a connection, but there was nothing to consume, while what really happens is that you can't connect (at all or for a specific tracing session).

> *[Reviewable](https://reviewable.io/reviews/eepp/babeltrace/19#-:-LcnPb130P0c-4f5u7W9:blys39i)* status: all files reviewed, 47 unresolved discussions (waiting on @frdeso)



<!-- Sent from Reviewable.io -->

2019-04-22 15:26 UTC, frdeso reviewed
> *[Reviewable](https://reviewable.io/reviews/eepp/babeltrace/19)* status: all files reviewed, 45 unresolved discussions (waiting on @eepp)

___
*[plugins/ctf/plugin.c, line 40 at r1](https://reviewable.io/reviews/eepp/babeltrace/19#-LclMQvJClZw2Qpdhu8h:-LcluNn492eOuq4lXF0L:b-896fix) ([raw file](https://github.com/eepp/babeltrace/blob/8d954d21f0d27252bf4a90dbd7e4d408a594cd1f/plugins/ctf/plugin.c#L40)):*
<details><summary><i>Previously, eepp (Philippe Proulx) wrote…</i></summary><blockquote>

Use an identifier, not a C string.
</blockquote></details>

Done.
___
*[plugins/ctf/lttng-live/data-stream.c, line 78 at r1](https://reviewable.io/reviews/eepp/babeltrace/19#-LclJIby8xE_4FsF3X4W:-LcmYkF_DtzC_ZHn2HgH:b-896fix) ([raw file](https://github.com/eepp/babeltrace/blob/8d954d21f0d27252bf4a90dbd7e4d408a594cd1f/plugins/ctf/lttng-live/data-stream.c#L78)):*
<details><summary><i>Previously, eepp (Philippe Proulx) wrote…</i></summary><blockquote>

`bt_stream_create_with_id()` accepts an unsigned ID.

`stream_id` is signed here because it is possible that the stream's packet header did not contain any stream ID. Or is it?

Consider that `stream_id` can be negative. If the LTTng live protocol makes this impossible (stream ID always exists), then check this in the metadata once at some other location and `BT_ASSERT()` here that it's the case, or return an error here if `stream_id` is negative. Otherwise you need to find an unused ID for the call to `bt_stream_create()`.
</blockquote></details>

Done.
___
*[plugins/ctf/lttng-live/data-stream.c, line 93 at r1](https://reviewable.io/reviews/eepp/babeltrace/19#-LclN1sR6mbyxC-v6bw9:-LcmFcZb4J_qPGJdFZCi:b-896fix) ([raw file](https://github.com/eepp/babeltrace/blob/8d954d21f0d27252bf4a90dbd7e4d408a594cd1f/plugins/ctf/lttng-live/data-stream.c#L93)):*
<details><summary><i>Previously, eepp (Philippe Proulx) wrote…</i></summary><blockquote>

Single tab to indent continuation (check other locations too).
</blockquote></details>

Done.
___
*[plugins/ctf/lttng-live/lttng-live.h, line 67 at r1](https://reviewable.io/reviews/eepp/babeltrace/19#-LclO2k8E3u3qJdo1NB4:-LcmbxfF79VMHILybC-I:b-896fix) ([raw file](https://github.com/eepp/babeltrace/blob/8d954d21f0d27252bf4a90dbd7e4d408a594cd1f/plugins/ctf/lttng-live/lttng-live.h#L67)):*
<details><summary><i>Previously, eepp (Philippe Proulx) wrote…</i></summary><blockquote>

Please, for everything that is shared as `stream`, add a comment at the top of the member to indicate if it's weak or "owned by this".
</blockquote></details>

Done.
___
*[plugins/ctf/lttng-live/lttng-live.h, line 84 at r1](https://reviewable.io/reviews/eepp/babeltrace/19#-LclNhkyAgbJ2FoxAyVF:-Lcmf_Lq6m9AbaiwiJMw:b-896fix) ([raw file](https://github.com/eepp/babeltrace/blob/8d954d21f0d27252bf4a90dbd7e4d408a594cd1f/plugins/ctf/lttng-live/lttng-live.h#L84)):*
<details><summary><i>Previously, eepp (Philippe Proulx) wrote…</i></summary><blockquote>

Are those clock snapshot values (I believe they should?), or timestamps in nanoseconds? Comment.
</blockquote></details>

Done.
___
*[plugins/ctf/lttng-live/lttng-live.h, line 88 at r1](https://reviewable.io/reviews/eepp/babeltrace/19#-LclNnIv2gjQZqMNayyv:-Lcmbz523vOzLdQsv-kb:b-896fix) ([raw file](https://github.com/eepp/babeltrace/blob/8d954d21f0d27252bf4a90dbd7e4d408a594cd1f/plugins/ctf/lttng-live/lttng-live.h#L88)):*
<details><summary><i>Previously, eepp (Philippe Proulx) wrote…</i></summary><blockquote>

Owned by this? Comment.
</blockquote></details>

Done.
___
*[plugins/ctf/lttng-live/lttng-live.h, line 89 at r1](https://reviewable.io/reviews/eepp/babeltrace/19#-LclNqq71Cgp6YxbofVX:-LcmfamPBzcda_rDL4FQ:b-896fix) ([raw file](https://github.com/eepp/babeltrace/blob/8d954d21f0d27252bf4a90dbd7e4d408a594cd1f/plugins/ctf/lttng-live/lttng-live.h#L89)):*
<details><summary><i>Previously, eepp (Philippe Proulx) wrote…</i></summary><blockquote>

CS value or ns? Comment.
</blockquote></details>

Done.
___
*[plugins/ctf/lttng-live/lttng-live.h, line 118 at r1](https://reviewable.io/reviews/eepp/babeltrace/19#-LclOIC1C9aezBo5AzIW:-Lcm0ggf9cFqeTayzS6F:b-896fix) ([raw file](https://github.com/eepp/babeltrace/blob/8d954d21f0d27252bf4a90dbd7e4d408a594cd1f/plugins/ctf/lttng-live/lttng-live.h#L118)):*
<details><summary><i>Previously, eepp (Philippe Proulx) wrote…</i></summary><blockquote>

Use `bool`.
</blockquote></details>

Done.
___
*[plugins/ctf/lttng-live/lttng-live.h, line 135 at r1](https://reviewable.io/reviews/eepp/babeltrace/19#-LclOOCN-F2H8tnP8we_:-Lcm0hBg7GRqxGiibrLm:b-896fix) ([raw file](https://github.com/eepp/babeltrace/blob/8d954d21f0d27252bf4a90dbd7e4d408a594cd1f/plugins/ctf/lttng-live/lttng-live.h#L135)):*
<details><summary><i>Previously, eepp (Philippe Proulx) wrote…</i></summary><blockquote>

`bool` for all those.
</blockquote></details>

Done.
___
*[plugins/ctf/lttng-live/lttng-live.h, line 151 at r1](https://reviewable.io/reviews/eepp/babeltrace/19#-LclOiIp3349rQU-MqWA:-LcmdSay1HELv2JaqyLk:b-896fix) ([raw file](https://github.com/eepp/babeltrace/blob/8d954d21f0d27252bf4a90dbd7e4d408a594cd1f/plugins/ctf/lttng-live/lttng-live.h#L151)):*
<details><summary><i>Previously, eepp (Philippe Proulx) wrote…</i></summary><blockquote>

Please comment about this.
</blockquote></details>

Done.
___
*[plugins/ctf/lttng-live/lttng-live.h, line 154 at r1](https://reviewable.io/reviews/eepp/babeltrace/19#-LclOp96-nXGZ65b2XPv:-LcmdqQX5WLfLwKfm7MM:b-896fix) ([raw file](https://github.com/eepp/babeltrace/blob/8d954d21f0d27252bf4a90dbd7e4d408a594cd1f/plugins/ctf/lttng-live/lttng-live.h#L154)):*
<details><summary><i>Previously, eepp (Philippe Proulx) wrote…</i></summary><blockquote>

Comment about the ownership of each pointer member.
</blockquote></details>

Done.
___
*[plugins/ctf/lttng-live/lttng-live.c, line 130 at r1](https://reviewable.io/reviews/eepp/babeltrace/19#-LclJf6-8xEFFJP0Marr:-Lcm117m8lrwIVN4wId4:b-896fix) ([raw file](https://github.com/eepp/babeltrace/blob/8d954d21f0d27252bf4a90dbd7e4d408a594cd1f/plugins/ctf/lttng-live/lttng-live.c#L130)):*
<details><summary><i>Previously, eepp (Philippe Proulx) wrote…</i></summary><blockquote>

Can we have a single return point (`end` label, etc.) for this one?
</blockquote></details>

Done.
___
*[plugins/ctf/lttng-live/lttng-live.c, line 139 at r1](https://reviewable.io/reviews/eepp/babeltrace/19#-LclQANdACCymO1BrgNq:-Lcm15MA-xKaKfj3uhLp:b-896fix) ([raw file](https://github.com/eepp/babeltrace/blob/8d954d21f0d27252bf4a90dbd7e4d408a594cd1f/plugins/ctf/lttng-live/lttng-live.c#L139)):*
<details><summary><i>Previously, eepp (Philippe Proulx) wrote…</i></summary><blockquote>

Use `BT_LOGD()`.
</blockquote></details>

Done.
___
*[plugins/ctf/lttng-live/lttng-live.c, line 147 at r1](https://reviewable.io/reviews/eepp/babeltrace/19#-LclQR8I-Q5DFgHNJPEC:-Lcm1FYH-duYDFKDMrv8:b-896fix) ([raw file](https://github.com/eepp/babeltrace/blob/8d954d21f0d27252bf4a90dbd7e4d408a594cd1f/plugins/ctf/lttng-live/lttng-live.c#L147)):*
<details><summary><i>Previously, eepp (Philippe Proulx) wrote…</i></summary><blockquote>

The "put ref and reset" macros check for `NULL`, so you don't need to check it again here. Same thing for `trace->trace` above.
</blockquote></details>

Done.
___
*[plugins/ctf/lttng-live/lttng-live.c, line 190 at r1](https://reviewable.io/reviews/eepp/babeltrace/19#-LclQkOME5trXLVeAYr4:-Lcm1Q5Y8JbSHVnFi4zh:b-896fix) ([raw file](https://github.com/eepp/babeltrace/blob/8d954d21f0d27252bf4a90dbd7e4d408a594cd1f/plugins/ctf/lttng-live/lttng-live.c#L190)):*
<details><summary><i>Previously, eepp (Philippe Proulx) wrote…</i></summary><blockquote>

Please use single return point.
</blockquote></details>

Done.
___
*[plugins/ctf/lttng-live/lttng-live.c, line 215 at r1](https://reviewable.io/reviews/eepp/babeltrace/19#-LclQqgv48rrGV9W2a0o:-Lcm1aGo4x553DIqKSN9:b-896fix) ([raw file](https://github.com/eepp/babeltrace/blob/8d954d21f0d27252bf4a90dbd7e4d408a594cd1f/plugins/ctf/lttng-live/lttng-live.c#L215)):*
<details><summary><i>Previously, eepp (Philippe P [...]

2019-04-22 15:31 UTC, frdeso commented
___
*[plugins/ctf/lttng-live/lttng-live.c, line 139 at r1](https://reviewable.io/reviews/eepp/babeltrace/19#-LclQANdACCymO1BrgNq:-Ld4egSy5TATPpShl3nI:bve64vn) ([raw file](https://github.com/eepp/babeltrace/blob/8d954d21f0d27252bf4a90dbd7e4d408a594cd1f/plugins/ctf/lttng-live/lttng-live.c#L139)):*
<details><summary><i>Previously, frdeso (Francis Deslauriers) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

immediate message


<!-- Sent from Reviewable.io -->

2019-04-22 16:02 UTC, frdeso commented
BT1.5 exits with success if no session of the requested name is found on the relay daemon.
It's returns an error if it could not connect to the relay at all.





<!-- Sent from Reviewable.io -->

2019-04-22 16:03 UTC, frdeso commented
So, I believe we want to keep that behavior.





<!-- Sent from Reviewable.io -->

2019-04-22 17:05 UTC, eepp requested changes
> BT1.5 exits with success if no session of the requested name is found on the relay daemon.
> It's returns an error if it could not connect to the relay at all.

> So, I believe we want to keep that behavior.

You mean the CLI, which is now `babeltrace convert`. The CLI should keep the behaviour of BT 1.5 indeed, but is it the best default for the component itself?

Maybe the component's default behaviour is to fail when the tracing session is not found, or the message iterator returns an end status instead when given a specific parameter (for example, `fail-on-session-not-found=no`). Then maybe this parameter can be combined with the `retry` parameter if we think about it.

> Reviewed 7 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/eepp/babeltrace/19#-:-Ld4qqwf6f-y8d2szZPE:bipfjlc)* status: all files reviewed, 17 unresolved discussions (waiting on @frdeso)

___
*[plugins/ctf/lttng-live/data-stream.c, line 100 at r3](https://reviewable.io/reviews/eepp/babeltrace/19#-Ld4sqHf0urSv1I_Z5cL:-Ld4sqHf0urSv1I_Z5cM:b-8c6x8y) ([raw file](https://github.com/eepp/babeltrace/blob/30ef7eece3e51cd0c724046f91441f090161b918/plugins/ctf/lttng-live/data-stream.c#L100)):*
> ```C
> 				lttng_live_stream->viewer_stream_id);
> 		} else {
> 			BT_ASSERT(stream_id >= 0);
> ```

Or just check `stream_id < 0` above and remove this `BT_ASSERT()`.
___
*[plugins/ctf/lttng-live/lttng-live.h, line 192 at r3](https://reviewable.io/reviews/eepp/babeltrace/19#-Ld4tYW13c2ljXnFswLZ:-Ld4tYW13c2ljXnFswL_:bqxj6t2) ([raw file](https://github.com/eepp/babeltrace/blob/30ef7eece3e51cd0c724046f91441f090161b918/plugins/ctf/lttng-live/lttng-live.h#L192)):*
> ```objc
> 
> 	/*
> 	 * Keeps track of whether the downstream component already an message
> ```

already _has a_ I guess
___
*[plugins/ctf/lttng-live/lttng-live.h, line 211 at r3](https://reviewable.io/reviews/eepp/babeltrace/19#-Ld4ti46911aPf9kF6tD:-Ld4ti46911aPf9kF6tE:b3sha) ([raw file](https://github.com/eepp/babeltrace/blob/30ef7eece3e51cd0c724046f91441f090161b918/plugins/ctf/lttng-live/lttng-live.h#L211)):*
> ```objc
> 	GPtrArray *sessions;
> 
> 	/* */
> ```

❓
___
*[plugins/ctf/lttng-live/lttng-live.c, line 1124 at r1](https://reviewable.io/reviews/eepp/babeltrace/19#-LclKgST7sQuu1kkjKJH:-Ld4xA1UBO81FmaiIj_T:b9p6qfh) ([raw file](https://github.com/eepp/babeltrace/blob/8d954d21f0d27252bf4a90dbd7e4d408a594cd1f/plugins/ctf/lttng-live/lttng-live.c#L1124)):*
> Are UST 32bit, and UST 64bit different domains?

No I just wanted to be confident.
___
*[plugins/ctf/lttng-live/lttng-live.c, line 97 at r3](https://reviewable.io/reviews/eepp/babeltrace/19#-Ld4vS8z4TeEYPbEVWuQ:-Ld4vS9-AztsHLqHEOov:b-o0cnzn) ([raw file](https://github.com/eepp/babeltrace/blob/30ef7eece3e51cd0c724046f91441f090161b918/plugins/ctf/lttng-live/lttng-live.c#L97)):*
> ```C
> 
> static
> void print_stream_state(struct lttng_live_stream_iterator *stream)
> ```

I'm wondering: don't you want a macro instead of this function so that you get the correct file names and line numbers in the log?
___
*[plugins/ctf/lttng-live/lttng-live.c, line 133 at r3](https://reviewable.io/reviews/eepp/babeltrace/19#-Ld4ty233jXbUCuGngdE:-Ld4ty233jXbUCuGngdF:b2zyuvh) ([raw file](https://github.com/eepp/babeltrace/blob/30ef7eece3e51cd0c724046f91441f090161b918/plugins/ctf/lttng-live/lttng-live.c#L133)):*
> ```C
> 
> 	for (trace_idx = 0; trace_idx < session->traces->len; trace_idx++) {
> 		trace = g_ptr_array_index(session->traces, trace_idx);
> ```

In this pattern, I think it's more readable to have another local trace variable here and assign it to `trace` when there's a match instead of resetting `trace` to `NULL` every time.

Just a personal choice, nothing blocking.
___
*[plugins/ctf/lttng-live/lttng-live.c, line 296 at r3](https://reviewable.io/reviews/eepp/babeltrace/19#-Ld4v6SyDnE-jCOCgWbp:-Ld4v6SyDnE-jCOCgWbq:bsnp2re) ([raw file](https://github.com/eepp/babeltrace/blob/30ef7eece3e51cd0c724046f91441f090161b918/plugins/ctf/lttng-live/lttng-live.c#L296)):*
> ```C
> 	BT_OBJECT_PUT_REF_AND_RESET(lttng_live_msg_iter->viewer_connection);
> 	BT_ASSERT(lttng_live_msg_iter->lttng_live_comp);
> 	BT_ASSERT(lttng_live_msg_iter->lttng_live_comp->has_msg_iter == true);
> ```

Superfluous.
___
*[plugins/ctf/lttng-live/lttng-live.c, line 300 at r3](https://reviewable.io/reviews/eepp/babeltrace/19#-Ld4vCETEoFAlwMbTzKM:-Ld4vCETEoFAlwMbTzKN:bsnp2re) ([raw file](https://github.com/eepp/babeltrace/blob/30ef7eece3e51cd0c724046f91441f090161b918/plugins/ctf/lttng-live/lttng-live.c#L300)):*
> ```C
> 	/* All stream iterators must be destroyed at this point. */
> 	BT_ASSERT(lttng_live_msg_iter->active_stream_iter == 0);
> 	lttng_live_msg_iter->lttng_live_comp->has_msg_iter = false;
> ```

Superfluous.
___
*[plugins/ctf/lttng-live/lttng-live.c, line 417 at r3](https://reviewable.io/reviews/eepp/babeltrace/19#-Ld4vqsm9fwtYtmlM9IT:-Ld4vqsm9fwtYtmlM9IU:bsnp2re) ([raw file](https://github.com/eepp/babeltrace/blob/30ef7eece3e51cd0c724046f91441f090161b918/plugins/ctf/lttng-live/lttng-live.c#L417)):*
> ```C
> 	int ret = 0;
> 
> 	if (session->attached == false) {
> ```

Superfluous.
___
*[plugins/ctf/lttng-live/lttng-live.c, line 1071 at r3](https://reviewable.io/reviews/eepp/babeltrace/19#-Ld4wljW9EiQ0lk1yqhu:-Ld4wljW9EiQ0lk1yqhv:bsnp2re) ([raw file](https://github.com/eepp/babeltrace/blob/30ef7eece3e51cd0c724046f91441f090161b918/plugins/ctf/lttng-live/lttng-live.c#L1071)):*
> ```C
> 		}
> 
> 		if (trace_is_ended == false) {
> ```

Superfluous.
___
*[plugins/ctf/lttng-live/lttng-live.c, line 1242 at r3](https://reviewable.io/reviews/eepp/babeltrace/19#-Ld4y0ub8VpiPIp2h-qt:-Ld4y0ub8VpiPIp2h-qu:b-4kepj7) ([raw file](https://github.com/eepp/babeltrace/blob/30ef7eece3e51cd0c724046f91441f090161b918/plugins/ctf/lttng-live/lttng-live.c#L1242)):*
> msgs[0] may not be NULL or may not be a valid message. We can't call put_ref() on it.

Then don't use `BT_MESSAGE_MOVE_REF()`; do like you did before.

Or read comment below about using `memset()`, in which case you can use `BT_MESSAGE_MOVE_REF()` and remove

    msgs[*count] = NULL;
___
*[plugins/ctf/lttng-live/lttng-live.c, line 1278 at r3](https://reviewable.io/reviews/eepp/babeltrace/19#-Ld4yJ-eB8fhBsX-RhfW:-Ld4yJ-eB8fhBsX-RhfX:be967uz) ([raw file](https://github.com/eepp/babeltrace/blob/30ef7eece3e51cd0c724046f91441f090161b918/plugins/ctf/lttng-live/lttng-live.c#L1278)):*
> ```C
> 		status = BT_SELF_MESSAGE_ITERATOR_STATUS_ERROR;
> 		/* Put all existing messages on error. */
> 		put_messages(msgs, *count);
> ```

It's possible at this point that some messages in this array were not set at all. One solution is to use `memset()` at the beginning of the function to set all references to `NULL`.
___
*[plugins/ctf/lttng-live/lttng-live.c, line 1473 at r3](https://reviewable.io/reviews/eepp/babeltrace/19#-Ld4ymMk8q-eNsNXizX0:-Ld4ymMk8q-eNsNXizX1:bf4oio7) ([raw file](https://github.com/eepp/babeltrace/blob/30ef7eece3e51cd0c724046f91441f090161b918/plugins/ctf/lttng-live/lttng-live.c#L1473)):*
> ```C
> 			lttng_live->params.retry = bt_value_bool_get(value);
> 		} else {
> 			BT_LOGW("Optional \"retry\" parameter is null or not a bool.");
> ```

Not exact anymore.

You can combine both conditions into `value && (bt_value_is_bool(value)` and change this message to _... is missing or not a boolean value._
___
*[plugins/ctf/lttng-live/metadata.c, line 74 at r3](https://reviewable.io/reviews/eepp/babeltrace/19#-Ld4z9d3DQE9CClEFTCZ:-Ld4z9d3DQE9CClEFTC_:b-jekc8c) ([raw file](https://github.com/eepp/babeltrace/blob/30ef7eece3e51cd0c724046f91441f090161b918/plugins/ctf/lttng-live/metadata.c#L74)):*
> ```C
> 		if (!cc) {
> 			ret = false;
> 			BT_LOGE("Stream class doesn't have a default clock class: sc-addr=%p", sc);
> ```

Stream class's ID and name would be more useful than its run time address.
___
*[plugins/ctf/lttng-live/viewer-connection.c, line 406 at r1](https://reviewable.io/reviews/eepp/babeltrace/19#-Lclm3KD-PiPkbAp0Za5:-Ld4zt-09XRPu5SCIkp4:b-jdstwb) ([raw file](https://git [...]

2019-04-22 17:50 UTC, frdeso commented
___
*[plugins/ctf/lttng-live/viewer-connection.c, line 406 at r1](https://reviewable.io/reviews/eepp/babeltrace/19#-Lclm3KD-PiPkbAp0Za5:-Ld598vn2PavQrCC_72c:b4e8a4l) ([raw file](https://github.com/eepp/babeltrace/blob/8d954d21f0d27252bf4a90dbd7e4d408a594cd1f/plugins/ctf/lttng-live/viewer-connection.c#L406)):*
<details><summary><i>Previously, eepp (Philippe Proulx) wrote…</i></summary><blockquote>

I don't think so. `_ERROR` is enough with appropriate logging.
</blockquote></details>

There is no BT_VALUE_STATUS__ERROR. I can add it.
```
typedef enum bt_value_status {
	/// Operation canceled.
	BT_VALUE_STATUS_CANCELED	= 125,

	/// Cannot allocate memory.
	BT_VALUE_STATUS_NOMEM		= -12,

	/// Okay, no error.
	BT_VALUE_STATUS_OK		= 0,
} bt_value_status;
```


<!-- Sent from Reviewable.io -->

2019-04-22 18:39 UTC, frdeso commented
___
*[plugins/ctf/lttng-live/lttng-live.c, line 300 at r3](https://reviewable.io/reviews/eepp/babeltrace/19#-Ld4vCETEoFAlwMbTzKM:-Ld5Jrd0CbsC5a5mDE_f:b-26m01r) ([raw file](https://github.com/eepp/babeltrace/blob/30ef7eece3e51cd0c724046f91441f090161b918/plugins/ctf/lttng-live/lttng-live.c#L300)):*
<details><summary><i>Previously, eepp (Philippe Proulx) wrote…</i></summary><blockquote>

Superfluous.
</blockquote></details>

Are you referring to the `BT_ASSERT()` statement above or the `= false` statement?
In the first case, I believe it helps readability to have an explicit comparison against 0.
In the second case, we need to set it to false so that the downstream iterator can create new iterator if it wishes so.


<!-- Sent from Reviewable.io -->

2019-04-22 19:35 UTC, frdeso commented
ok I understand what you mean about the CLI versus the component.
Can you explain the differences between your proposed `fail-on-session-not-found=no` and `retry=yes`?





<!-- Sent from Reviewable.io -->

2019-04-22 20:39 UTC, frdeso reviewed
> *[Reviewable](https://reviewable.io/reviews/eepp/babeltrace/19)* status: 8 of 17 files reviewed, 16 unresolved discussions (waiting on @eepp)

___
*[plugins/ctf/lttng-live/data-stream.c, line 100 at r3](https://reviewable.io/reviews/eepp/babeltrace/19#-Ld4sqHf0urSv1I_Z5cL:-Ld5AUyHDlpZlsROwewP:b-896fix) ([raw file](https://github.com/eepp/babeltrace/blob/30ef7eece3e51cd0c724046f91441f090161b918/plugins/ctf/lttng-live/data-stream.c#L100)):*
<details><summary><i>Previously, eepp (Philippe Proulx) wrote…</i></summary><blockquote>

Or just check `stream_id < 0` above and remove this `BT_ASSERT()`.
</blockquote></details>

Done.
___
*[plugins/ctf/lttng-live/lttng-live.h, line 192 at r3](https://reviewable.io/reviews/eepp/babeltrace/19#-Ld4tYW13c2ljXnFswLZ:-Ld5AaYt1lh7K5si5a-b:b-896fix) ([raw file](https://github.com/eepp/babeltrace/blob/30ef7eece3e51cd0c724046f91441f090161b918/plugins/ctf/lttng-live/lttng-live.h#L192)):*
<details><summary><i>Previously, eepp (Philippe Proulx) wrote…</i></summary><blockquote>

already _has a_ I guess
</blockquote></details>

Done.
___
*[plugins/ctf/lttng-live/lttng-live.h, line 211 at r3](https://reviewable.io/reviews/eepp/babeltrace/19#-Ld4ti46911aPf9kF6tD:-Ld5CmJRB-VaWtDLlcBy:b-896fix) ([raw file](https://github.com/eepp/babeltrace/blob/30ef7eece3e51cd0c724046f91441f090161b918/plugins/ctf/lttng-live/lttng-live.h#L211)):*
<details><summary><i>Previously, eepp (Philippe Proulx) wrote…</i></summary><blockquote>

❓
</blockquote></details>

Done.
___
*[plugins/ctf/lttng-live/lttng-live.c, line 1124 at r1](https://reviewable.io/reviews/eepp/babeltrace/19#-LclKgST7sQuu1kkjKJH:-Ld5DON9B5bOhlaNt70a:b-896fix) ([raw file](https://github.com/eepp/babeltrace/blob/8d954d21f0d27252bf4a90dbd7e4d408a594cd1f/plugins/ctf/lttng-live/lttng-live.c#L1124)):*
<details><summary><i>Previously, eepp (Philippe Proulx) wrote…</i></summary><blockquote>

> Are UST 32bit, and UST 64bit different domains?

No I just wanted to be confident.
</blockquote></details>

Done.
___
*[plugins/ctf/lttng-live/lttng-live.c, line 296 at r3](https://reviewable.io/reviews/eepp/babeltrace/19#-Ld4v6SyDnE-jCOCgWbp:-Ld5CsaDCbftvWTBrd3t:b-896fix) ([raw file](https://github.com/eepp/babeltrace/blob/30ef7eece3e51cd0c724046f91441f090161b918/plugins/ctf/lttng-live/lttng-live.c#L296)):*
<details><summary><i>Previously, eepp (Philippe Proulx) wrote…</i></summary><blockquote>

Superfluous.
</blockquote></details>

Done.
___
*[plugins/ctf/lttng-live/lttng-live.c, line 417 at r3](https://reviewable.io/reviews/eepp/babeltrace/19#-Ld4vqsm9fwtYtmlM9IT:-Ld5DJTQ3G9-DIkFySVE:b-896fix) ([raw file](https://github.com/eepp/babeltrace/blob/30ef7eece3e51cd0c724046f91441f090161b918/plugins/ctf/lttng-live/lttng-live.c#L417)):*
<details><summary><i>Previously, eepp (Philippe Proulx) wrote…</i></summary><blockquote>

Superfluous.
</blockquote></details>

Done.
___
*[plugins/ctf/lttng-live/lttng-live.c, line 1071 at r3](https://reviewable.io/reviews/eepp/babeltrace/19#-Ld4wljW9EiQ0lk1yqhu:-Ld5DK759gbszi9Kf0Vm:b-896fix) ([raw file](https://github.com/eepp/babeltrace/blob/30ef7eece3e51cd0c724046f91441f090161b918/plugins/ctf/lttng-live/lttng-live.c#L1071)):*
<details><summary><i>Previously, eepp (Philippe Proulx) wrote…</i></summary><blockquote>

Superfluous.
</blockquote></details>

Done.
___
*[plugins/ctf/lttng-live/lttng-live.c, line 1242 at r3](https://reviewable.io/reviews/eepp/babeltrace/19#-Ld4y0ub8VpiPIp2h-qt:-Ld5NxqdEV6yAiP8MPOF:b-896fix) ([raw file](https://github.com/eepp/babeltrace/blob/30ef7eece3e51cd0c724046f91441f090161b918/plugins/ctf/lttng-live/lttng-live.c#L1242)):*
<details><summary><i>Previously, eepp (Philippe Proulx) wrote…</i></summary><blockquote>

> msgs[0] may not be NULL or may not be a valid message. We can't call put_ref() on it.

Then don't use `BT_MESSAGE_MOVE_REF()`; do like you did before.

Or read comment below about using `memset()`, in which case you can use `BT_MESSAGE_MOVE_REF()` and remove

    msgs[*count] = NULL;
</blockquote></details>

Done.
___
*[plugins/ctf/lttng-live/lttng-live.c, line 1278 at r3](https://reviewable.io/reviews/eepp/babeltrace/19#-Ld4yJ-eB8fhBsX-RhfW:-Ld5Nxe665oRHo6ePWgD:b-896fix) ([raw file](https://github.com/eepp/babeltrace/blob/30ef7eece3e51cd0c724046f91441f090161b918/plugins/ctf/lttng-live/lttng-live.c#L1278)):*
<details><summary><i>Previously, eepp (Philippe Proulx) wrote…</i></summary><blockquote>

It's possible at this point that some messages in this array were not set at all. One solution is to use `memset()` at the beginning of the function to set all references to `NULL`.
</blockquote></details>

Done.
___
*[plugins/ctf/lttng-live/lttng-live.c, line 1473 at r3](https://reviewable.io/reviews/eepp/babeltrace/19#-Ld4ymMk8q-eNsNXizX0:-Ld5FyvQ8WwcFt5t7YWb:b-896fix) ([raw file](https://github.com/eepp/babeltrace/blob/30ef7eece3e51cd0c724046f91441f090161b918/plugins/ctf/lttng-live/lttng-live.c#L1473)):*
<details><summary><i>Previously, eepp (Philippe Proulx) wrote…</i></summary><blockquote>

Not exact anymore.

You can combine both conditions into `value && (bt_value_is_bool(value)` and change this message to _... is missing or not a boolean value._
</blockquote></details>

Done.
___
*[plugins/ctf/lttng-live/metadata.c, line 74 at r3](https://reviewable.io/reviews/eepp/babeltrace/19#-Ld4z9d3DQE9CClEFTCZ:-Ld5ELNK70PX6Po5dAgc:b-896fix) ([raw file](https://github.com/eepp/babeltrace/blob/30ef7eece3e51cd0c724046f91441f090161b918/plugins/ctf/lttng-live/metadata.c#L74)):*
<details><summary><i>Previously, eepp (Philippe Proulx) wrote…</i></summary><blockquote>

Stream class's ID and name would be more useful than its run time address.
</blockquote></details>

Done.
___
*[plugins/ctf/lttng-live/viewer-connection.c, line 67 at r3](https://reviewable.io/reviews/eepp/babeltrace/19#-Ld4zVhA4U3LTUwo-Fw4:-Ld5EVx75E9vWIbkwO23:b-896fix) ([raw file](https://github.com/eepp/babeltrace/blob/30ef7eece3e51cd0c724046f91441f090161b918/plugins/ctf/lttng-live/viewer-connection.c#L67)):*
<details><summary><i>Previously, eepp (Philippe Proulx) wrote…</i></summary><blockquote>

Superfluous.
</blockquote></details>

Done.
___
*[plugins/ctf/lttng-live/viewer-connection.c, line 93 at r3](https://reviewable.io/reviews/eepp/babeltrace/19#-Ld4zXNJAmFWktG--5FH:-Ld5EWIF1S5inC9_jmNg:b-896fix) ([raw file](https://github.com/eepp/babeltrace/blob/30ef7eece3e51cd0c724046f91441f090161b918/plugins/ctf/lttng-live/viewer-connection.c#L93)):*
<details><summary><i>Previously, eepp (Philippe Proulx) wrote…</i></summary><blockquote>

Superfluous.
</blockquote></details>

Done.
___
*[plugins/ctf/lttng-live/viewer-connection.c, line 312 at r3](https://reviewable.io/reviews/eepp/babeltrace/19#-Ld4z_hL1FcF6av07ikK:-Ld5Gl5P4J4dXKMLjEo-:b-896fix) ([raw file](https://github.com/eepp/babeltrace/blob/30ef7eece3e51cd0c724046f91441f090161b918/plugins/ctf/lttng-live/viewer-connection.c#L312)):*
<details><summary><i>Previously, eepp (Philippe Proulx) wrote…</i></summary><blockquote>

`bool` (search for `bt_bool|BT_(TRUE|FALSE)` in the whole plugin and eliminate the internal ones).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-04-22 20:40 UTC, frdeso commented
*[a discussion](https://reviewable.io/reviews/eepp/babeltrace/19#-Ld5l_lz4RX8rAK-pCkF:-Ld5l_lz4RX8rAK-pCkG:b5osasf) (no related file):*
I included a new commit to disable the printing of the message iterator inactivity message handling to stderr.

---


<!-- Sent from Reviewable.io -->

2019-04-22 22:58 UTC, eepp requested changes
> Can you explain the differences between your proposed fail-on-session-not-found=no and retry=yes?

In fact what about having this default behaviour: the message iterator "subscribes" using the given URL (so, as of this day, a specific relay daemon and a specific session name), and when the iterator would be ended, it just keeps on retrying to connect and get new data, never finishing.

Then we have those parameters:

* `subscribe` (boolean): if it exists and it's false, disable this subscription mode. The iterator ends as soon as there's no data.
* `fail-on-session-not-found` (boolean): if it exists and it's true, and the mode is `subscribe=no`, then make the component initialization fail when it cannot find the given session name; otherwise do the old behaviour (make the iterator be ended initially so that the whole graph ends successfully). This cannot be combined with `subscribe=yes`.

> Reviewed 9 of 9 files at r4.
> *[Reviewable](https://reviewable.io/reviews/eepp/babeltrace/19#-:-Ld6ErnuA621t-IlrvEL:b44ohly)* status: all files reviewed, 4 unresolved discussions (waiting on @frdeso)

___
*[plugins/ctf/lttng-live/lttng-live.c, line 300 at r3](https://reviewable.io/reviews/eepp/babeltrace/19#-Ld4vCETEoFAlwMbTzKM:-Ld6CnIbEkU6TNCueWKW:by8c0sk) ([raw file](https://github.com/eepp/babeltrace/blob/30ef7eece3e51cd0c724046f91441f090161b918/plugins/ctf/lttng-live/lttng-live.c#L300)):*
<details><summary><i>Previously, frdeso (Francis Deslauriers) wrote…</i></summary><blockquote>

Are you referring to the `BT_ASSERT()` statement above or the `= false` statement?
In the first case, I believe it helps readability to have an explicit comparison against 0.
In the second case, we need to set it to false so that the downstream iterator can create new iterator if it wishes so.

</blockquote></details>

No this is a mistake from me, sorry.
___
*[plugins/ctf/lttng-live/metadata.c, line 75 at r4](https://reviewable.io/reviews/eepp/babeltrace/19#-Ld6DGKx58oDwOTcEjkr:-Ld6DGKx58oDwOTcEjks:b-sgfb5h) ([raw file](https://github.com/eepp/babeltrace/blob/a7cdc7fc283f15ee2c4f3cd43bcbeda82b2d3845/plugins/ctf/lttng-live/metadata.c#L75)):*
> ```C
> 			ret = false;
> 			BT_LOGE("Stream class doesn't have a default clock "
> 				"class: sc-id=%" PRIu64 ", sc-name=%s",
> ```

`sc-name=\"%s\"` and please put this `class: ` (with the space) on the line above even if the line is too long; it's easier to search a logging message in the whole code this way.
___
*[plugins/ctf/lttng-live/viewer-connection.c, line 406 at r1](https://reviewable.io/reviews/eepp/babeltrace/19#-Lclm3KD-PiPkbAp0Za5:-Ld6DeDn8yjj3VGi3_HV:b-pgj5np) ([raw file](https://github.com/eepp/babeltrace/blob/8d954d21f0d27252bf4a90dbd7e4d408a594cd1f/plugins/ctf/lttng-live/viewer-connection.c#L406)):*
<details><summary><i>Previously, frdeso (Francis Deslauriers) wrote…</i></summary><blockquote>

There is no BT_VALUE_STATUS__ERROR. I can add it.
```
typedef enum bt_value_status {
	/// Operation canceled.
	BT_VALUE_STATUS_CANCELED	= 125,

	/// Cannot allocate memory.
	BT_VALUE_STATUS_NOMEM		= -12,

	/// Okay, no error.
	BT_VALUE_STATUS_OK		= 0,
} bt_value_status;
```
</blockquote></details>

Oh right, cause this API does not need it. Then just return `int` from this function and use -1 for a generic error.
___
*[plugins/text/pretty/pretty.c, line 145 at r4](https://reviewable.io/reviews/eepp/babeltrace/19#-Ld6E61a5pxY_JbeYJ7v:-Ld6E61a5pxY_JbeYJ7w:b-hsss1g) ([raw file](https://github.com/eepp/babeltrace/blob/a7cdc7fc283f15ee2c4f3cd43bcbeda82b2d3845/plugins/text/pretty/pretty.c#L145)):*
> ```C
> 		break;
> 	case BT_MESSAGE_TYPE_MESSAGE_ITERATOR_INACTIVITY:
> 		BT_LOGD("Message iterator inactivity message.");
> ```

Use `BT_LOGD_STR()`.


<!-- Sent from Reviewable.io -->

2019-04-23 02:38 UTC, frdeso commented
If I understand correctly this is the behavior for all the combination of parameter values. Is that right?
```
+-----------+-----------------+-----------------------+-------------------------+------------------------+
| Subscribe | Fail-no-session |       Comp init       |       no session        |    no more session     |
+-----------+-----------------+-----------------------+-------------------------+------------------------+
| no        | no              | -                     | STATUS_END              | STATUS_END             |
| no        | yes             | -                     | Fail                    | STATUS_END             |
| yes       | no              | -                     | keep trying to connect  | keep trying to connect |
| yes       | yes             | Fail. Invalid config. | NA                      | NA                     |
+-----------+-----------------+-----------------------+-------------------------+------------------------+

```





<!-- Sent from Reviewable.io -->

2019-04-23 03:05 UTC, frdeso reviewed
> *[Reviewable](https://reviewable.io/reviews/eepp/babeltrace/19)* status: 14 of 17 files reviewed, 3 unresolved discussions (waiting on @eepp)

___
*[plugins/ctf/lttng-live/metadata.c, line 75 at r4](https://reviewable.io/reviews/eepp/babeltrace/19#-Ld6DGKx58oDwOTcEjkr:-Ld6bqcB19DNeJXm4oTk:b-896fix) ([raw file](https://github.com/eepp/babeltrace/blob/a7cdc7fc283f15ee2c4f3cd43bcbeda82b2d3845/plugins/ctf/lttng-live/metadata.c#L75)):*
<details><summary><i>Previously, eepp (Philippe Proulx) wrote…</i></summary><blockquote>

`sc-name=\"%s\"` and please put this `class: ` (with the space) on the line above even if the line is too long; it's easier to search a logging message in the whole code this way.
</blockquote></details>

Done.
___
*[plugins/ctf/lttng-live/viewer-connection.c, line 406 at r1](https://reviewable.io/reviews/eepp/babeltrace/19#-Lclm3KD-PiPkbAp0Za5:-Ld6wM-O5epYJLlQQLR5:b-896fix) ([raw file](https://github.com/eepp/babeltrace/blob/8d954d21f0d27252bf4a90dbd7e4d408a594cd1f/plugins/ctf/lttng-live/viewer-connection.c#L406)):*
<details><summary><i>Previously, eepp (Philippe Proulx) wrote…</i></summary><blockquote>

Oh right, cause this API does not need it. Then just return `int` from this function and use -1 for a generic error.
</blockquote></details>

Done.
___
*[plugins/text/pretty/pretty.c, line 145 at r4](https://reviewable.io/reviews/eepp/babeltrace/19#-Ld6E61a5pxY_JbeYJ7v:-Ld6cSBR8waUMaeS3bC3:b-896fix) ([raw file](https://github.com/eepp/babeltrace/blob/a7cdc7fc283f15ee2c4f3cd43bcbeda82b2d3845/plugins/text/pretty/pretty.c#L145)):*
<details><summary><i>Previously, eepp (Philippe Proulx) wrote…</i></summary><blockquote>

Use `BT_LOGD_STR()`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-04-23 15:48 UTC, eepp requested changes
> If I understand correctly this is the behavior for all the combination of parameter values. Is that right?

Is is the component initialization which establishes a connection, or the message iterator initialization?

If it's the former, then without subscription, but with "fail on session not found", the component needs to fail at initialization time.

Otherwise the rest of the table looks okay.

> Reviewed 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/eepp/babeltrace/19#-:-Ld9s5tt86na1rBeTzKE:b-42438s)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2019-04-23 16:02 UTC, frdeso commented
The connection is established in the message iterator initialization.





<!-- Sent from Reviewable.io -->

2019-04-23 17:00 UTC, eepp commented
Oh I see. Then your table is accurate.

But since there's an invalid configuration, we could have a single `session-not-found-action` parameter with three choices:

* `retry` (or `continue`?) (default)
* `end`
* `fail`

WDYT?





<!-- Sent from Reviewable.io -->

2019-04-23 22:16 UTC, eepp requested changes
> Reviewed 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/eepp/babeltrace/19)* status: all files reviewed, 4 unresolved discussions (waiting on @frdeso)

___
*[plugins/ctf/lttng-live/lttng-live.c, line 1362 at r6](https://reviewable.io/reviews/eepp/babeltrace/19#-LdBEVZg3U_1R_Dp6Uzs:-LdBEVZg3U_1R_Dp6Uzt:bxb9n5f) ([raw file](https://github.com/eepp/babeltrace/blob/728e15794bec543eeb16a3a8c02c672070f5e72c/plugins/ctf/lttng-live/lttng-live.c#L1362)):*
> ```C
> 		switch (lttng_live->params.sess_not_found_act) {
> 		case SESSION_NOT_FOUND_ACTION_CONTINUE:
> 			BT_LOGI("Unable to connect to the requested live viewer "
> ```

For both those `BT_LOGI()` calls, can you also include the configured URL in the `: url=\"%s\"` form?
___
*[plugins/ctf/lttng-live/lttng-live.c, line 1375 at r6](https://reviewable.io/reviews/eepp/babeltrace/19#-LdBEFc2ELe7YU25YNv9:-LdBEFc2ELe7YU25YNvA:b-s3hmk9) ([raw file](https://github.com/eepp/babeltrace/blob/728e15794bec543eeb16a3a8c02c672070f5e72c/plugins/ctf/lttng-live/lttng-live.c#L1375)):*
> ```C
> 				SESS_NOT_FOUND_ACTION_FAIL_STR);
> 			goto error;
> 			break;
> ```

Not needed.
___
*[plugins/ctf/lttng-live/lttng-live.c, line 1522 at r6](https://reviewable.io/reviews/eepp/babeltrace/19#-LdBF21A8g1i-B8fi3ga:-LdBF21A8g1i-B8fi3gb:b-ew2gua) ([raw file](https://github.com/eepp/babeltrace/blob/728e15794bec543eeb16a3a8c02c672070f5e72c/plugins/ctf/lttng-live/lttng-live.c#L1522)):*
> ```C
> 
> 	value = bt_value_map_borrow_entry_value_const(params, URL_PARAM);
> 	if (!value || bt_value_is_null(value) || !bt_value_is_string(value)) {
> ```

I just saw that: `bt_value_is_null()` is useless.
___
*[plugins/ctf/lttng-live/lttng-live.c, line 1539 at r6](https://reviewable.io/reviews/eepp/babeltrace/19#-LdBFCf8-BWKaXWaeugF:-LdBFCf8-BWKaXWaeugG:bjwmylw) ([raw file](https://github.com/eepp/babeltrace/blob/728e15794bec543eeb16a3a8c02c672070f5e72c/plugins/ctf/lttng-live/lttng-live.c#L1539)):*
> ```C
> 			parse_session_not_found_action_param(value);
> 		if (lttng_live->params.sess_not_found_act == -1) {
> 			BT_LOGE("Optional \"%s\" string parameter of unknown "
> ```

Can you use the form where variables are at the end like this:

    Unexpected value for `session-not-found-action` parameter: value="something"


<!-- Sent from Reviewable.io -->

2019-04-24 01:21 UTC, frdeso commented
___
*[plugins/ctf/lttng-live/lttng-live.c, line 1362 at r6](https://reviewable.io/reviews/eepp/babeltrace/19#-LdBEVZg3U_1R_Dp6Uzs:-LdBtQp82KM5Uz2fPWKl:b-3aw2wb) ([raw file](https://github.com/eepp/babeltrace/blob/728e15794bec543eeb16a3a8c02c672070f5e72c/plugins/ctf/lttng-live/lttng-live.c#L1362)):*
<details><summary><i>Previously, eepp (Philippe Proulx) wrote…</i></summary><blockquote>

For both those `BT_LOGI()` calls, can you also include the configured URL in the `: url=\"%s\"` form?
</blockquote></details>

Done. but why not add it to the `BT_LOGE()` too?


<!-- Sent from Reviewable.io -->

2019-04-24 01:32 UTC, frdeso reviewed
> *[Reviewable](https://reviewable.io/reviews/eepp/babeltrace/19)* status: 16 of 17 files reviewed, 4 unresolved discussions (waiting on @eepp)

___
*[plugins/ctf/lttng-live/lttng-live.c, line 1375 at r6](https://reviewable.io/reviews/eepp/babeltrace/19#-LdBEFc2ELe7YU25YNv9:-LdBtRbV5XUlljPcnqZn:b-896fix) ([raw file](https://github.com/eepp/babeltrace/blob/728e15794bec543eeb16a3a8c02c672070f5e72c/plugins/ctf/lttng-live/lttng-live.c#L1375)):*
<details><summary><i>Previously, eepp (Philippe Proulx) wrote…</i></summary><blockquote>

Not needed.
</blockquote></details>

Done.
___
*[plugins/ctf/lttng-live/lttng-live.c, line 1522 at r6](https://reviewable.io/reviews/eepp/babeltrace/19#-LdBF21A8g1i-B8fi3ga:-LdBtZf68BWKtZvYdJ5N:b-896fix) ([raw file](https://github.com/eepp/babeltrace/blob/728e15794bec543eeb16a3a8c02c672070f5e72c/plugins/ctf/lttng-live/lttng-live.c#L1522)):*
<details><summary><i>Previously, eepp (Philippe Proulx) wrote…</i></summary><blockquote>

I just saw that: `bt_value_is_null()` is useless.
</blockquote></details>

Done.
___
*[plugins/ctf/lttng-live/lttng-live.c, line 1539 at r6](https://reviewable.io/reviews/eepp/babeltrace/19#-LdBFCf8-BWKaXWaeugF:-LdBuoXT4u16vTnjEndg:b-896fix) ([raw file](https://github.com/eepp/babeltrace/blob/728e15794bec543eeb16a3a8c02c672070f5e72c/plugins/ctf/lttng-live/lttng-live.c#L1539)):*
<details><summary><i>Previously, eepp (Philippe Proulx) wrote…</i></summary><blockquote>

Can you use the form where variables are at the end like this:

    Unexpected value for `session-not-found-action` parameter: value="something"
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-04-24 04:47 UTC, eepp reviewed
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/eepp/babeltrace/19)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[plugins/ctf/lttng-live/lttng-live.c, line 1362 at r6](https://reviewable.io/reviews/eepp/babeltrace/19#-LdBEVZg3U_1R_Dp6Uzs:-LdCdu211liM7bf5qoW0:brz2agd) ([raw file](https://github.com/eepp/babeltrace/blob/728e15794bec543eeb16a3a8c02c672070f5e72c/plugins/ctf/lttng-live/lttng-live.c#L1362)):*
<details><summary><i>Previously, frdeso (Francis Deslauriers) wrote…</i></summary><blockquote>

Done. but why not add it to the `BT_LOGE()` too?
</blockquote></details>

Yes, ideally have it everywhere, at least for the INFO, WARN, and ERROR levels. This can be valuable information for a bug report.

You can make your own macros which wrap `BT_LOGI()`, `BT_LOGW()` and so on which accept a `struct lttng_live *` (or a message iterator) parameter and log the same basic contextual information every time.


<!-- Sent from Reviewable.io -->

2019-04-24 15:22 UTC, eepp approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/eepp/babeltrace/19#-:-LdEwBOy62eXv3ByMWSb:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2019-04-24 15:25 UTC, merged