Support for session rotation (multiple traces with same UUID)
eepp/babeltrace pull request #30
Opened 2019-04-22 15:08 UTC by simark

This set of patches adds support for Babeltrace to treat multiple CTF traces that have the same UUID as a single trace.

I have written tests using the Python API, but since the Python API is still broken in this branch, I have left them out.

2019-04-22 22:39 UTC, eepp requested changes
## Replies

> The code should be pretty self-explanatory/commented.

This is implicit 😉.

> I have remove or updated references to --key/--value in man pages.

Can you also document the updated `--params` format, both in the C file and in the man page? I'll go over this later to harmonize the documentation style, but at least the content will exist.

> There are no functional changes intended, except if you are the kind of person to pass params by hand to the src.ctf.fs component.

😆

## General

LGTM in general. Many comments are about the coding style, and most of them are:

* How to stylize a block comment.
* Declare variables at beginning of scope.
* Use a single return point.
* Name the end-of-function label `end` (instead of `error`) when it's not only reached on error.

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 4 of 4 files at r4, 1 of 1 files at r5, 6 of 6 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/eepp/babeltrace/30#-:-Ld53Uc-8EDZIrm74zDv:b-e8tgu4)* status: all files reviewed, 77 unresolved discussions (waiting on @simark)

___
*[bindings/python/bt2/bt2/trace_collection_notification_iterator.py, line 132 at r6](https://reviewable.io/reviews/eepp/babeltrace/30#-Ld5CoYxA6yJwZdgQVzC:-Ld5CoYyBI2dPOurqXW4:b-3m8ver) ([raw file](https://github.com/eepp/babeltrace/blob/2742efdbb6f43a3fdb879fee2bab325effea17a6/bindings/python/bt2/bt2/trace_collection_notification_iterator.py#L132)):*
> ```Python
> 
>         try:
>             paths = src_comp_and_spec.spec.params['paths']
> ```

I'll just mark this (Python) as accepted for the moment and review all Python in their own pull request instead.
___
*[cli/babeltrace.c, line 2169 at r6](https://reviewable.io/reviews/eepp/babeltrace/30#-Ld5D6Ae8Q8ILOY-amof:-Ld5D6Ae8Q8ILOY-amog:b-71wwey) ([raw file](https://github.com/eepp/babeltrace/blob/2742efdbb6f43a3fdb879fee2bab325effea17a6/cli/babeltrace.c#L2169)):*
> ```C
> 
> 	ret = query(comp_cls, "trace-info",
> 		cfg_comp->params, &query_result,
> ```

This is cleaner indeed.
___
*[cli/babeltrace-cfg-cli-args.c, line 200 at r1](https://reviewable.io/reviews/eepp/babeltrace/30#-Ld51EHw9M7M3Mhacc3-:-Ld51EHw9M7M3Mhacc30:b8cfdpr) ([raw file](https://github.com/eepp/babeltrace/blob/7eaee4faf2635481e4da381faeeff4a55b7a2097/cli/babeltrace-cfg-cli-args.c#L200)):*
> ```C
> 		uint64_t int_val = state->scanner->value.v_int64;
> 
> 		if (int_val > (1ULL << 63) - 1) {
> ```

Use `UINT64_C(INT64_MAX)`.
___
*[cli/babeltrace-cfg-cli-args.c, line 205 at r1](https://reviewable.io/reviews/eepp/babeltrace/30#-Ld51oo8AO05RrgYSU4Y:-Ld51oo8AO05RrgYSU4Z:b-df989g) ([raw file](https://github.com/eepp/babeltrace/blob/7eaee4faf2635481e4da381faeeff4a55b7a2097/cli/babeltrace-cfg-cli-args.c#L205)):*
> ```C
> 				int_val);
> 		} else {
> 			value = bt_value_integer_create_init(-((int64_t)int_val));
> ```

Space after cast.
___
*[cli/babeltrace-cfg-cli-args.c, line 305 at r1](https://reviewable.io/reviews/eepp/babeltrace/30#-Ld52-nF1Mgoxsn4pX_W:-Ld52-nF1Mgoxsn4pX_X:bqcv37d) ([raw file](https://github.com/eepp/babeltrace/blob/7eaee4faf2635481e4da381faeeff4a55b7a2097/cli/babeltrace-cfg-cli-args.c#L305)):*
> ```C
> 				/* Negative number */
> 				value = ini_parse_neg_number(state);
> 				if (value == NULL) {
> ```

As @jgalar recommended for the project, use the `!value` style here.
___
*[cli/babeltrace-cfg-cli-args.c, line 222 at r2](https://reviewable.io/reviews/eepp/babeltrace/30#-Ld5343G2yedBX0Yzcqr:-Ld5343G2yedBX0Yzcqs:b-v6e12g) ([raw file](https://github.com/eepp/babeltrace/blob/93f432bc4ccb821bbec9eb18eded678382c3af59/cli/babeltrace-cfg-cli-args.c#L222)):*
> ```C
> }
> 
> /* Parse the current token (and the following ones if needed) as a value, return
> ```

```
/*
 * write here
 */
```
___
*[cli/babeltrace-cfg-cli-args.c, line 224 at r3](https://reviewable.io/reviews/eepp/babeltrace/30#-Ld53ZYGDQ362_4jn3VA:-Ld53ZYGDQ362_4jn3VB:b-pm0h00) ([raw file](https://github.com/eepp/babeltrace/blob/3036c8f8c333d01c8a1e7c2599f5ca8701fd3418/cli/babeltrace-cfg-cli-args.c#L224)):*
> ```C
> static bt_value *ini_parse_value(struct ini_parsing_state *state);
> 
> /* Parse the current and following tokens as an array.  The current token should
> ```

```
/*
 *
 */
```

Also: _should_ ➡️ _must_.
___
*[cli/babeltrace-cfg-cli-args.c, line 229 at r3](https://reviewable.io/reviews/eepp/babeltrace/30#-Ld53lCn7X8CRxWbLeeb:-Ld53lCn7X8CRxWbLeec:b-9p8yo5) ([raw file](https://github.com/eepp/babeltrace/blob/3036c8f8c333d01c8a1e7c2599f5ca8701fd3418/cli/babeltrace-cfg-cli-args.c#L229)):*
> ```C
> bt_value *ini_parse_array(struct ini_parsing_state *state)
> {
> 	/* The [ character should have already been ingested. */
> ```

_should_ ➡️ _must_
___
*[cli/babeltrace-cfg-cli-args.c, line 246 at r3](https://reviewable.io/reviews/eepp/babeltrace/30#-Ld54ewY9hJeo9fur_tz:-Ld54ewY9hJeo9fur_u-:b-5svy76) ([raw file](https://github.com/eepp/babeltrace/blob/3036c8f8c333d01c8a1e7c2599f5ca8701fd3418/cli/babeltrace-cfg-cli-args.c#L246)):*
> ```C
> 
> 		/* ... and add it to the result array. */
> 		bt_value_array_append_element(array_value, item_value);
> ```

This can fail (no memory).

If you're confident enough that it won't, at least `BT_ASSERT()` that the returned status is `BT_VALUE_STATUS_OK`.

Note that if it fails, this loop still owns the `item_value` reference.
___
*[cli/babeltrace-cfg-cli-args.c, line 249 at r3](https://reviewable.io/reviews/eepp/babeltrace/30#-Ld54PAE3NZQ7fCNPO3J:-Ld54PAE3NZQ7fCNPO3K:b2v3yv7) ([raw file](https://github.com/eepp/babeltrace/blob/3036c8f8c333d01c8a1e7c2599f5ca8701fd3418/cli/babeltrace-cfg-cli-args.c#L249)):*
> ```C
> 		bt_value_put_ref(item_value);
> 
> 		/* Ingest the token following the value, it should be either a
> ```

Apply project's block comment style.
___
*[cli/babeltrace-cfg-cli-args.c, line 254 at r3](https://reviewable.io/reviews/eepp/babeltrace/30#-Ld54RV_BRbptVLFCsT9:-Ld54RV_BRbptVLFCsTA:b2v3yv7) ([raw file](https://github.com/eepp/babeltrace/blob/3036c8f8c333d01c8a1e7c2599f5ca8701fd3418/cli/babeltrace-cfg-cli-args.c#L254)):*
> ```C
> 
> 		if (token_type == G_TOKEN_CHAR && g_scanner_cur_value(state->scanner).v_char == ',') {
> 			/* Ingest the token following the comma.  If it happens
> ```

Apply project's block comment style.
___
*[cli/babeltrace-cfg-cli-args.c, line 260 at r3](https://reviewable.io/reviews/eepp/babeltrace/30#-Ld54JaR7FOvNieKKsxe:-Ld54JaR7FOvNieKKsxf:blkvwfg) ([raw file](https://github.com/eepp/babeltrace/blob/3036c8f8c333d01c8a1e7c2599f5ca8701fd3418/cli/babeltrace-cfg-cli-args.c#L260)):*
> ```C
> 			token_type = g_scanner_get_next_token(state->scanner);
> 		} else if (token_type == G_TOKEN_CHAR && g_scanner_cur_value(state->scanner).v_char == ']') {
> 			/* Nothing, we'll exit the loop and we're done. */
> ```

Then why do we have a conditional for this?
___
*[cli/babeltrace-cfg-cli-args.c, line 267 at r3](https://reviewable.io/reviews/eepp/babeltrace/30#-Ld541HPBB37tdoJWWWa:-Ld541HPBB37tdoJWWWb:bu7clh7) ([raw file](https://github.com/eepp/babeltrace/blob/3036c8f8c333d01c8a1e7c2599f5ca8701fd3418/cli/babeltrace-cfg-cli-args.c#L267)):*
> ```C
> 	}
> 
> 	return array_value;
> ```

We use a single return point.

The practice is having a `goto end` here, and an `end` label following the `error` label which returns `array_value`. The error block resets the variable as it already does below.
___
*[cli/babeltrace-cfg-cli-args.c, line 25 at r4](https://reviewable.io/reviews/eepp/babeltrace/30#-Ld55KG1Azzgcya_44wY:-Ld55KG23eJC51PIC8Xx:b1ijhct) ([raw file](https://github.com/eepp/babeltrace/blob/b996a6ccf01ddec992d5ab4bce36872f1a8cddd6/cli/babeltrace-cfg-cli-args.c#L25)):*
> ```C
>  */
> 
> #include "babeltrace/value-const.h"
> ```

We use `<>` for this.
___
*[cli/babeltrace-cfg-cli-args.c, line 3153 at r4](https://reviewable.io/reviews/eepp/babeltrace/30#-Ld56JQy3g2nHZJ8B5-X:-Ld56JQy3g2nHZJ8B5-Y:b-otsi99) ([raw file](https://github.com/eepp/babeltrace/blob/b996a6ccf01ddec992d5ab4bce36872f1a8cddd6/cli/babel [...]

2019-04-23 18:54 UTC, simark reviewed
> Can you also document the updated --params format, both in the C file and in the man page? I'll go over this later to harmonize the documentation style, but at least the content will exist.

Done.  In the C file, I have put it in the doc of the `ini_parse_array` function, tell me if there would be a better place for it.

> *[Reviewable](https://reviewable.io/reviews/eepp/babeltrace/30#-:-Ld9ebs294tRyv7NjJbq:bowo2v2)* status: all files reviewed, 76 unresolved discussions (waiting on @eepp and @jgalar)

___
*[bindings/python/bt2/bt2/trace_collection_notification_iterator.py, line 132 at r6](https://reviewable.io/reviews/eepp/babeltrace/30#-Ld5CoYxA6yJwZdgQVzC:-Ld6z6it4f8xv-FxxJ3t:bcqz7mp) ([raw file](https://github.com/eepp/babeltrace/blob/2742efdbb6f43a3fdb879fee2bab325effea17a6/bindings/python/bt2/bt2/trace_collection_notification_iterator.py#L132)):*
<details><summary><i>Previously, eepp (Philippe Proulx) wrote…</i></summary><blockquote>

I'll just mark this (Python) as accepted for the moment and review all Python in their own pull request instead.
</blockquote></details>

I can also remove it from the patch and put it with the upcoming Python binding stuff, maybe it would make more sense to have it there.
___
*[cli/babeltrace-cfg-cli-args.c, line 200 at r1](https://reviewable.io/reviews/eepp/babeltrace/30#-Ld51EHw9M7M3Mhacc3-:-Ld6uFQb9-xRll9XXN09:b-pqccts) ([raw file](https://github.com/eepp/babeltrace/blob/7eaee4faf2635481e4da381faeeff4a55b7a2097/cli/babeltrace-cfg-cli-args.c#L200)):*
<details><summary><i>Previously, eepp (Philippe Proulx) wrote…</i></summary><blockquote>

Use `UINT64_C(INT64_MAX)`.
</blockquote></details>

Note: this is pre-existing code I moved around, so I will do that change as a separate commit (in this patchset) so it is easier to track down if needed.


`UINT64_C(INT64_MAX)` doesn't build, since `INT64_MAX` already includes a suffix.  And I think that pedantically, `-(INT64_MAX + 1)` is within the acceptable range, since a 64-bit two's complement has the range `[-2**63, 2**63]`.  So I would use

    if (int_val > (((uint64_t) INT64_MAX) + 1)) {

I just tried it and it produces the expected result of accepting -9223372036854775808 but rejecting -9223372036854775809.
___
*[cli/babeltrace-cfg-cli-args.c, line 205 at r1](https://reviewable.io/reviews/eepp/babeltrace/30#-Ld51oo8AO05RrgYSU4Y:-Ld6xEDK91pHjKK6ZeYp:b-896fix) ([raw file](https://github.com/eepp/babeltrace/blob/7eaee4faf2635481e4da381faeeff4a55b7a2097/cli/babeltrace-cfg-cli-args.c#L205)):*
<details><summary><i>Previously, eepp (Philippe Proulx) wrote…</i></summary><blockquote>

Space after cast.
</blockquote></details>

Done.
___
*[cli/babeltrace-cfg-cli-args.c, line 305 at r1](https://reviewable.io/reviews/eepp/babeltrace/30#-Ld52-nF1Mgoxsn4pX_W:-Ld9UPJ10rL6rvZqrlbT:b-896fix) ([raw file](https://github.com/eepp/babeltrace/blob/7eaee4faf2635481e4da381faeeff4a55b7a2097/cli/babeltrace-cfg-cli-args.c#L305)):*
<details><summary><i>Previously, eepp (Philippe Proulx) wrote…</i></summary><blockquote>

As @jgalar recommended for the project, use the `!value` style here.
</blockquote></details>

Done.
___
*[cli/babeltrace-cfg-cli-args.c, line 222 at r2](https://reviewable.io/reviews/eepp/babeltrace/30#-Ld5343G2yedBX0Yzcqr:-Ld7-wLsEh726U9W6sR3:b-896fix) ([raw file](https://github.com/eepp/babeltrace/blob/93f432bc4ccb821bbec9eb18eded678382c3af59/cli/babeltrace-cfg-cli-args.c#L222)):*
<details><summary><i>Previously, eepp (Philippe Proulx) wrote…</i></summary><blockquote>

```
/*
 * write here
 */
```
</blockquote></details>

Done.
___
*[cli/babeltrace-cfg-cli-args.c, line 224 at r3](https://reviewable.io/reviews/eepp/babeltrace/30#-Ld53ZYGDQ362_4jn3VA:-Ld6zIZh1n3AilAhVBVK:b-896fix) ([raw file](https://github.com/eepp/babeltrace/blob/3036c8f8c333d01c8a1e7c2599f5ca8701fd3418/cli/babeltrace-cfg-cli-args.c#L224)):*
<details><summary><i>Previously, eepp (Philippe Proulx) wrote…</i></summary><blockquote>

```
/*
 *
 */
```

Also: _should_ ➡️ _must_.
</blockquote></details>

Done.
___
*[cli/babeltrace-cfg-cli-args.c, line 229 at r3](https://reviewable.io/reviews/eepp/babeltrace/30#-Ld53lCn7X8CRxWbLeeb:-Ld6zJld01bGwhNXEanC:b-vd0d8r) ([raw file](https://github.com/eepp/babeltrace/blob/3036c8f8c333d01c8a1e7c2599f5ca8701fd3418/cli/babeltrace-cfg-cli-args.c#L229)):*
<details><summary><i>Previously, eepp (Philippe Proulx) wrote…</i></summary><blockquote>

_should_ ➡️ _must_
</blockquote></details>

Hmm, apple must (done).
___
*[cli/babeltrace-cfg-cli-args.c, line 246 at r3](https://reviewable.io/reviews/eepp/babeltrace/30#-Ld54ewY9hJeo9fur_tz:-Ld6yIyM8HzN5PpiPg8c:b-ajgcbz) ([raw file](https://github.com/eepp/babeltrace/blob/3036c8f8c333d01c8a1e7c2599f5ca8701fd3418/cli/babeltrace-cfg-cli-args.c#L246)):*
<details><summary><i>Previously, eepp (Philippe Proulx) wrote…</i></summary><blockquote>

This can fail (no memory).

If you're confident enough that it won't, at least `BT_ASSERT()` that the returned status is `BT_VALUE_STATUS_OK`.

Note that if it fails, this loop still owns the `item_value` reference.
</blockquote></details>

I added the check.
___
*[cli/babeltrace-cfg-cli-args.c, line 249 at r3](https://reviewable.io/reviews/eepp/babeltrace/30#-Ld54PAE3NZQ7fCNPO3J:-Ld6zQb1D3gWzXuV5Eqm:b-896fix) ([raw file](https://github.com/eepp/babeltrace/blob/3036c8f8c333d01c8a1e7c2599f5ca8701fd3418/cli/babeltrace-cfg-cli-args.c#L249)):*
<details><summary><i>Previously, eepp (Philippe Proulx) wrote…</i></summary><blockquote>

Apply project's block comment style.
</blockquote></details>

Done.
___
*[cli/babeltrace-cfg-cli-args.c, line 254 at r3](https://reviewable.io/reviews/eepp/babeltrace/30#-Ld54RV_BRbptVLFCsT9:-Ld6zRJf4kWxi0RRk2MG:b-896fix) ([raw file](https://github.com/eepp/babeltrace/blob/3036c8f8c333d01c8a1e7c2599f5ca8701fd3418/cli/babeltrace-cfg-cli-args.c#L254)):*
<details><summary><i>Previously, eepp (Philippe Proulx) wrote…</i></summary><blockquote>

Apply project's block comment style.
</blockquote></details>

Done.
___
*[cli/babeltrace-cfg-cli-args.c, line 260 at r3](https://reviewable.io/reviews/eepp/babeltrace/30#-Ld54JaR7FOvNieKKsxe:-Ld6zWNYA4jJTpdGM1zy:blycheo) ([raw file](https://github.com/eepp/babeltrace/blob/3036c8f8c333d01c8a1e7c2599f5ca8701fd3418/cli/babeltrace-cfg-cli-args.c#L260)):*
<details><summary><i>Previously, eepp (Philippe Proulx) wrote…</i></summary><blockquote>

Then why do we have a conditional for this?
</blockquote></details>

So we don't go into the "else".  The alternative is to invert the condition and just have

```
		if (token_type == G_TOKEN_CHAR && g_scanner_cur_value(state->scanner).v_char == ',') {
			/*
			 * Ingest the token following the comma.  If it happens
			 * to be a closing square bracket, we'll exit the loop
			 * and we are done (we allow trailing commas).
			 * Otherwise, we are ready for the next ini_parse_value call.
			 */
			token_type = g_scanner_get_next_token(state->scanner);
		} else if (token_type != G_TOKEN_CHAR || g_scanner_cur_value(state->scanner).v_char != ']') {
			ini_append_error_expecting(state, state->scanner, ", or ]");
			goto error;
		}
```

But if I was reading it, I wouldn't understand the intent as well.  I don't mind changing it if it annoys you.
___
*[cli/babeltrace-cfg-cli-args.c, line 267 at r3](https://reviewable.io/reviews/eepp/babeltrace/30#-Ld541HPBB37tdoJWWWa:-Ld70AQtBRKXBtBAHEdg:b-896fix) ([raw file](https://github.com/eepp/babeltrace/blob/3036c8f8c333d01c8a1e7c2599f5ca8701fd3418/cli/babeltrace-cfg-cli-args.c#L267)):*
<details><summary><i>Previously, eepp (Philippe Proulx) wrote…</i></summary><blockquote>

We use a single return point.

The practice is having a `goto end` here, and an `end` label following the `error` label which returns `array_value`. The error block resets the variable as it already does below.
</blockquote></details>

Done.
___
*[cli/babeltrace-cfg-cli-args.c, line 25 at r4](https://reviewable.io/reviews/eepp/babeltrace/30#-Ld55KG1Azzgcya_44wY:-Ld6t_8X4TFnXUrdmvMt:b-sealx3) ([raw file]( [...]

2019-04-23 19:47 UTC, eepp requested changes
> tell me if there would be a better place for it

I meant for the end user (find _Expected format of PARAMS_ in the source file, and look at `common-cmd-params-format.txt`).

> *[Reviewable](https://reviewable.io/reviews/eepp/babeltrace/30#-:-LdAaiTm9aUofoxTXrt9:bv71eb6)* status: all files reviewed, 2 unresolved discussions (waiting on @simark)

___
*[bindings/python/bt2/bt2/trace_collection_notification_iterator.py, line 132 at r6](https://reviewable.io/reviews/eepp/babeltrace/30#-Ld5CoYxA6yJwZdgQVzC:-LdAbLJzDjb2gpKB34cc:b-j6bqx5) ([raw file](https://github.com/eepp/babeltrace/blob/2742efdbb6f43a3fdb879fee2bab325effea17a6/bindings/python/bt2/bt2/trace_collection_notification_iterator.py#L132)):*
<details><summary><i>Previously, simark (Simon Marchi) wrote…</i></summary><blockquote>

I can also remove it from the patch and put it with the upcoming Python binding stuff, maybe it would make more sense to have it there.
</blockquote></details>

Yes do this. 👍
___
*[cli/babeltrace-cfg-cli-args.c, line 200 at r1](https://reviewable.io/reviews/eepp/babeltrace/30#-Ld51EHw9M7M3Mhacc3-:-LdAbxmv6l6FvZ-0n-KJ:b-yo1h57) ([raw file](https://github.com/eepp/babeltrace/blob/7eaee4faf2635481e4da381faeeff4a55b7a2097/cli/babeltrace-cfg-cli-args.c#L200)):*
<details><summary><i>Previously, simark (Simon Marchi) wrote…</i></summary><blockquote>

Note: this is pre-existing code I moved around, so I will do that change as a separate commit (in this patchset) so it is easier to track down if needed.


`UINT64_C(INT64_MAX)` doesn't build, since `INT64_MAX` already includes a suffix.  And I think that pedantically, `-(INT64_MAX + 1)` is within the acceptable range, since a 64-bit two's complement has the range `[-2**63, 2**63]`.  So I would use

    if (int_val > (((uint64_t) INT64_MAX) + 1)) {

I just tried it and it produces the expected result of accepting -9223372036854775808 but rejecting -9223372036854775809.
</blockquote></details>

You're right about that `+ 1` because we're on the negative side. What we want is something like `-INT64_MIN` but what you suggest is alright.
___
*[cli/babeltrace-cfg-cli-args.c, line 229 at r3](https://reviewable.io/reviews/eepp/babeltrace/30#-Ld53lCn7X8CRxWbLeeb:-LdAcqyZBvjv9XGDwYxQ:b-sl8mh0) ([raw file](https://github.com/eepp/babeltrace/blob/3036c8f8c333d01c8a1e7c2599f5ca8701fd3418/cli/babeltrace-cfg-cli-args.c#L229)):*
<details><summary><i>Previously, simark (Simon Marchi) wrote…</i></summary><blockquote>

Hmm, apple must (done).
</blockquote></details>

🍎🍏🍎
___
*[cli/babeltrace-cfg-cli-args.c, line 260 at r3](https://reviewable.io/reviews/eepp/babeltrace/30#-Ld54JaR7FOvNieKKsxe:-LdAd2gz745U8UPC6A8T:bzh90e5) ([raw file](https://github.com/eepp/babeltrace/blob/3036c8f8c333d01c8a1e7c2599f5ca8701fd3418/cli/babeltrace-cfg-cli-args.c#L260)):*
<details><summary><i>Previously, simark (Simon Marchi) wrote…</i></summary><blockquote>

So we don't go into the "else".  The alternative is to invert the condition and just have

```
		if (token_type == G_TOKEN_CHAR && g_scanner_cur_value(state->scanner).v_char == ',') {
			/*
			 * Ingest the token following the comma.  If it happens
			 * to be a closing square bracket, we'll exit the loop
			 * and we are done (we allow trailing commas).
			 * Otherwise, we are ready for the next ini_parse_value call.
			 */
			token_type = g_scanner_get_next_token(state->scanner);
		} else if (token_type != G_TOKEN_CHAR || g_scanner_cur_value(state->scanner).v_char != ']') {
			ini_append_error_expecting(state, state->scanner, ", or ]");
			goto error;
		}
```

But if I was reading it, I wouldn't understand the intent as well.  I don't mind changing it if it annoys you.
</blockquote></details>

I don't care so much but I prefer to see the real condition than having empty conditionals. As you wish really.
___
*[cli/babeltrace-cfg-cli-args.c, line 3206 at r4](https://reviewable.io/reviews/eepp/babeltrace/30#-Ld56pQxA-Am4Hsdbzbj:-LdAhFnbBHMsK2KA5PZb:b3z495y) ([raw file](https://github.com/eepp/babeltrace/blob/b996a6ccf01ddec992d5ab4bce36872f1a8cddd6/cli/babeltrace-cfg-cli-args.c#L3206)):*
<details><summary><i>Previously, simark (Simon Marchi) wrote…</i></summary><blockquote>

Hmm, the difference in the other cases I found (in `append_run_args_for_implicit_component` and `bt_config_convert_from_args`) is that we receive the complete arg in the form `KEY=VALUE`, as a single string.  Formatting it as `--params=KEY=VALUE` would require us to do string formatting we don't need to do otherwise, so it just seems wasteful.

In this case, we need to do string formatting anyway, to join the key with the escaped value.  So to keep things simple at the other sites, if we want consistency, I'll choose to have separate `--params` and `KEY=VALUE` here.
</blockquote></details>

As you wish but I like the `--key=val` format because it matches the usage's and man page's format 🙂.

Not blocking at all though.
___
*[cli/babeltrace-cfg-cli-args.c, line 3187 at r5](https://reviewable.io/reviews/eepp/babeltrace/30#-Ld59EaY0kfB9bMMUHJL:-LdAdt7h2AQsbUA46Om7:b4saxk8) ([raw file](https://github.com/eepp/babeltrace/blob/94d628a9823820cd9e4a14777fa098d870c51c7a/cli/babeltrace-cfg-cli-args.c#L3187)):*
<details><summary><i>Previously, simark (Simon Marchi) wrote…</i></summary><blockquote>

Done... But may I suggest that we adopt the practice of always initialising variables that are going to be freed at the end of the function (either in the error or normal path)?  I understand that here, it's unnecessary, but it could help reduce accidental `free` of uninitialized variable in the future.  It's quite easy for somebody to add a new allocation before the use/assignation of `result`, and forget to then initialise `result` to `NULL`, which will then be necessary.

If the compiler sees the assignation/initialisation is unnecessary, I am sure it will optimise it away.
</blockquote></details>

I see this the other way. If you don't initialize it and you can reach a usage of this variable, then you can know right away that it's used (or could be) uninitialized because the compiler warns you. So should you use this variable in an unintended way in the future, you get the warning, and start having doubts about why you're using this variable, and about the meaning of your life in general.
___
*[cli/babeltrace-cfg-cli-args.c, line 3197 at r5](https://reviewable.io/reviews/eepp/babeltrace/30#-Ld59LLz32lFJonKycTu:-LdAgWpA5FUXAN9wSpEj:bpnxayf) ([raw file](https://github.com/eepp/babeltrace/blob/94d628a9823820cd9e4a14777fa098d870c51c7a/cli/babeltrace-cfg-cli-args.c#L3197)):*
<details><summary><i>Previously, simark (Simon Marchi) wrote…</i></summary><blockquote>

Done, but it sounds inconsistent with the placement of other scope-opening braces.
</blockquote></details>

Don't ask me why, but this is how it seems to be done in our projects: https://github.com/lttng/lttng-tools/blob/18710679a8ac57fda5dbd26cf16bb180dce9e286/src/lib/lttng-ctl/filter/filter-visitor-generate-ir.c#L877.
___
*[plugins/ctf/fs-src/fs.c, line 294 at r6](https://reviewable.io/reviews/eepp/babeltrace/30#-Ld5XEs8Bj4ChIa3GvTV:-LdAhfzG25KGnwtMF097:b-xd3vm6) ([raw file](https://github.com/eepp/babeltrace/blob/7e39a0feab0ebab3019482f7f0b7ca61181d9409/plugins/ctf/fs-src/fs.c#L294)):*
<details><summary><i>Previously, simark (Simon Marchi) wrote…</i></summary><blockquote>

Done.  Although I think it would make sense to only have them on the declaration.
</blockquote></details>

You're right.
___
*[plugins/ctf/fs-src/fs.c, line 1356 at r6](https://reviewable.io/reviews/eepp/babeltrace/30#-Ld5YfBA0leBv-TpNJpQ:-LdAin3GEPFi-zJNDi4A:bb76mu4) ([raw file](https://github.com/eepp/babeltrace/blob/2742efdbb6f43a3fdb879fee2bab325effea17a6/plugins/ctf/fs-src/fs.c#L1356)):*
<details><summary><i>Previously, simark (Simon Marchi) wrote…</i></summary><blockquote>

I now have both an error and end label.
</blockquote></details>

Why?
___
*[plugins/ctf/fs-src/fs.c, line 1391 at r7](https://reviewable.io/reviews/eepp/ [...]

2019-04-24 14:04 UTC, simark reviewed
> I meant for the end user (find Expected format of PARAMS in the source file, and look at common-cmd-params-format.txt).

Yes I did that for the user-facing documentation (the man pages), but you also told me to document it in the C file.  In the C file, I put it in the comment above the `ini_parse_array` function, but I was wondering if there was a better place for that.

> *[Reviewable](https://reviewable.io/reviews/eepp/babeltrace/30#-:-LdEaXHhAzrHMi17oy8V:bgrf5br)* status: all files reviewed, 1 unresolved discussion (waiting on @eepp)

___
*[bindings/python/bt2/bt2/trace_collection_notification_iterator.py, line 132 at r6](https://reviewable.io/reviews/eepp/babeltrace/30#-Ld5CoYxA6yJwZdgQVzC:-LdEb-tn-vynXhq-M6yK:bs7wumb) ([raw file](https://github.com/eepp/babeltrace/blob/2742efdbb6f43a3fdb879fee2bab325effea17a6/bindings/python/bt2/bt2/trace_collection_notification_iterator.py#L132)):*
<details><summary><i>Previously, eepp (Philippe Proulx) wrote…</i></summary><blockquote>

Yes do this. 👍
</blockquote></details>

Done.
___
*[cli/babeltrace-cfg-cli-args.c, line 200 at r1](https://reviewable.io/reviews/eepp/babeltrace/30#-Ld51EHw9M7M3Mhacc3-:-LdEb7pI9vp_V1F9YTYu:b-lg5dhd) ([raw file](https://github.com/eepp/babeltrace/blob/7eaee4faf2635481e4da381faeeff4a55b7a2097/cli/babeltrace-cfg-cli-args.c#L200)):*
<details><summary><i>Previously, eepp (Philippe Proulx) wrote…</i></summary><blockquote>

You're right about that `+ 1` because we're on the negative side. What we want is something like `-INT64_MIN` but what you suggest is alright.
</blockquote></details>

I don't know if something like `-INT64_MIN` would be valid (defined behavior), since `INT64_MIN` is most likely an int64_t value, and `-INT64_MIN` is not a value you can represent as an int64_t.  Anyway.
___
*[cli/babeltrace-cfg-cli-args.c, line 260 at r3](https://reviewable.io/reviews/eepp/babeltrace/30#-Ld54JaR7FOvNieKKsxe:-LdEb_PgBJRBBJkFOSUB:b-s8ohz9) ([raw file](https://github.com/eepp/babeltrace/blob/3036c8f8c333d01c8a1e7c2599f5ca8701fd3418/cli/babeltrace-cfg-cli-args.c#L260)):*
<details><summary><i>Previously, eepp (Philippe Proulx) wrote…</i></summary><blockquote>

I don't care so much but I prefer to see the real condition than having empty conditionals. As you wish really.
</blockquote></details>

I have changed it.
___
*[cli/babeltrace-cfg-cli-args.c, line 3206 at r4](https://reviewable.io/reviews/eepp/babeltrace/30#-Ld56pQxA-Am4Hsdbzbj:-LdEdi608zye7cOnmKLN:b-u6zxc) ([raw file](https://github.com/eepp/babeltrace/blob/b996a6ccf01ddec992d5ab4bce36872f1a8cddd6/cli/babeltrace-cfg-cli-args.c#L3206)):*
<details><summary><i>Previously, eepp (Philippe Proulx) wrote…</i></summary><blockquote>

As you wish but I like the `--key=val` format because it matches the usage's and man page's format 🙂.

Not blocking at all though.
</blockquote></details>

Yeah, we can always change it later, when there are urgent matters :).
___
*[cli/babeltrace-cfg-cli-args.c, line 3187 at r5](https://reviewable.io/reviews/eepp/babeltrace/30#-Ld59EaY0kfB9bMMUHJL:-LdEe1XS0RxF0ra5-QvE:b9hsjvh) ([raw file](https://github.com/eepp/babeltrace/blob/94d628a9823820cd9e4a14777fa098d870c51c7a/cli/babeltrace-cfg-cli-args.c#L3187)):*
<details><summary><i>Previously, eepp (Philippe Proulx) wrote…</i></summary><blockquote>

I see this the other way. If you don't initialize it and you can reach a usage of this variable, then you can know right away that it's used (or could be) uninitialized because the compiler warns you. So should you use this variable in an unintended way in the future, you get the warning, and start having doubts about why you're using this variable, and about the meaning of your life in general.
</blockquote></details>

It's true that we should get a warning (`-Wmaybe-uninitialized`), but with gcc 7.3.0 at least, I don't get a warning for this code, where `result` could be returned uninitialized:

```
static
gchar *bt_value_to_cli_param_value(bt_value *value)
{
	GString *buf;
	gchar *result;

	buf = g_string_new(NULL);
	if (!buf) {
		print_err_oom();
		goto error;
	}

	if (bt_value_to_cli_param_value_append(value, buf)) {
		goto error;
	}

	result = g_string_free(buf, FALSE);
	buf = NULL;

	goto end;

error:
	if (buf) {
		g_string_free(buf, TRUE);
	}

end:
	return result;
}
```
___
*[plugins/ctf/fs-src/fs.c, line 1356 at r6](https://reviewable.io/reviews/eepp/babeltrace/30#-Ld5YfBA0leBv-TpNJpQ:-LdEdu1ZBKT9TSWipi4h:biuuyc6) ([raw file](https://github.com/eepp/babeltrace/blob/2742efdbb6f43a3fdb879fee2bab325effea17a6/plugins/ctf/fs-src/fs.c#L1356)):*
<details><summary><i>Previously, eepp (Philippe Proulx) wrote…</i></summary><blockquote>

Why?
</blockquote></details>

I'll push a new revision soon.


<!-- Sent from Reviewable.io -->

2019-04-24 16:22 UTC, eepp requested changes
> but you also told me to document it in the C file

I meant for `--help`. Have a look at `print_expected_params_format()` and copy what you added to the man page, it's perfect.

> Reviewed 9 of 9 files at r8, 1 of 1 files at r9, 1 of 1 files at r10, 2 of 2 files at r11, 4 of 4 files at r12, 1 of 1 files at r13, 5 of 5 files at r14, 27 of 27 files at r15.
> *[Reviewable](https://reviewable.io/reviews/eepp/babeltrace/30#-:-LdF8YEl4FtFg9XF_XX5:b-22u3uc)* status: all files reviewed, 5 unresolved discussions (waiting on @simark)

___
*[cli/babeltrace-cfg-cli-args.c, line 3187 at r5](https://reviewable.io/reviews/eepp/babeltrace/30#-Ld59EaY0kfB9bMMUHJL:-LdF35XS-7AdNh4Nmdkq:be9s44k) ([raw file](https://github.com/eepp/babeltrace/blob/94d628a9823820cd9e4a14777fa098d870c51c7a/cli/babeltrace-cfg-cli-args.c#L3187)):*
<details><summary><i>Previously, simark (Simon Marchi) wrote…</i></summary><blockquote>

It's true that we should get a warning (`-Wmaybe-uninitialized`), but with gcc 7.3.0 at least, I don't get a warning for this code, where `result` could be returned uninitialized:

```
static
gchar *bt_value_to_cli_param_value(bt_value *value)
{
	GString *buf;
	gchar *result;

	buf = g_string_new(NULL);
	if (!buf) {
		print_err_oom();
		goto error;
	}

	if (bt_value_to_cli_param_value_append(value, buf)) {
		goto error;
	}

	result = g_string_free(buf, FALSE);
	buf = NULL;

	goto end;

error:
	if (buf) {
		g_string_free(buf, TRUE);
	}

end:
	return result;
}
```
</blockquote></details>

😱 This is sad.

In light of this catastrophic technology failure, I sanction you to initialize what you wish.
___
*[cli/babeltrace-cfg-cli-args.c, line 246 at r10](https://reviewable.io/reviews/eepp/babeltrace/30#-LdF0USjEzSBskMydwk9:-LdF0USjEzSBskMydwkA:bks77m2) ([raw file](https://github.com/eepp/babeltrace/blob/b7dce1ef8d2716aedf54dacccf4cd68b15e06e23/cli/babeltrace-cfg-cli-args.c#L246)):*
> ```C
> 		uint64_t int_val = state->scanner->value.v_int64;
> 
> 		if (int_val > INT64_MAX) {
> ```

So you don't need any explicit `(uint64_t)` cast here?

I would have thought the compiler complains about a signed-unsigned comparison.
___
*[plugins/ctf/fs-src/fs.c, line 1329 at r15](https://reviewable.io/reviews/eepp/babeltrace/30#-LdF6s-kB_VTyJRdwaBX:-LdF6s-kB_VTyJRdwaBY:b-daamxx) ([raw file](https://github.com/eepp/babeltrace/blob/4f816d5bc133e395365062e1d3ea38d42cc62a6c/plugins/ctf/fs-src/fs.c#L1329)):*
> ```C
>    traces sharing the same UUID.  It is assumed that amongst all these metadatas,
>    a bigger metadata is a superset of a smaller metadata.  Therefore, it is
>    enough to just count the classes. */
> ```

Minor: put `*/` below.
___
*[plugins/ctf/fs-src/fs.c, line 1387 at r15](https://reviewable.io/reviews/eepp/babeltrace/30#-LdF7A7VEBBChDHreMCe:-LdF7A7VEBBChDHreMCf:b655jyj) ([raw file](https://github.com/eepp/babeltrace/blob/4f816d5bc133e395365062e1d3ea38d42cc62a6c/plugins/ctf/fs-src/fs.c#L1387)):*
> ```C
> 		if (src_group->stream_id != -1) {
> 			/* Let's search for a matching ds_file_group in the destination.  */
> 			for (d_i = 0; d_i < dest_len; d_i++) {
> ```

FYI: you could declare `d_i` just above here, as long as it's at the beginning of a scope. It would be closer.
___
*[plugins/ctf/fs-src/fs.c, line 1398 at r15](https://reviewable.io/reviews/eepp/babeltrace/30#-LdF7Nfx5LegLKFTruhp:-LdF7Nfx5LegLKFTruhq:bf6elg6) ([raw file](https://github.com/eepp/babeltrace/blob/4f816d5bc133e395365062e1d3ea38d42cc62a6c/plugins/ctf/fs-src/fs.c#L1398)):*
> ```C
> 				   and belong to the same stream class (stream instance
> 				   ids are per-stream class), they represent the same
> 				   stream instance. */
> ```

Block comment style.
___
*[plugins/ctf/fs-src/fs.c, line 1400 at r15](https://reviewable.io/reviews/eepp/babeltrace/30#-LdF7RMY4ncjHKZdMCiG:-LdF7RMY4ncjHKZdMCiH:bqkllp9) ([raw file](https://github.com/eepp/babeltrace/blob/4f816d5bc133e395365062e1d3ea38d42cc62a6c/plugins/ctf/fs-src/fs.c#L1400)):*
> ```C
> 				   stream instance. */
> 				if (candidate_dest->stream_id != src_group->stream_id ||
> 					candidate_dest->sc->id != src_group->sc->id) {
> ```

Indent this one one more time.
___
*[plugins/ctf/fs-src/fs.c, line 1410 at r15](https://reviewable.io/reviews/eepp/babeltrace/30#-LdF7V10DPo_H9U4BNut:-LdF7V10DPo_H9U4BNuu:bf6elg6) ([raw file](https://github.com/eepp/babeltrace/blob/4f816d5bc133e395365062e1d3ea38d42cc62a6c/plugins/ctf/fs-src/fs.c#L1410)):*
> ```C
> 
> 		/* Didn't find a friend in dest to merge our src_group into?
> 		   Create a new empty one. */
> ```

Block comment style.


<!-- Sent from Reviewable.io -->

2019-04-24 18:04 UTC, simark reviewed
> I meant for --help. Have a look at print_expected_params_format() and copy what you added to the man page, it's perfect.

Ah ok, done.

> *[Reviewable](https://reviewable.io/reviews/eepp/babeltrace/30#-:-LdFWDpUEXK6AEkfSNmA:b-9why7v)* status: all files reviewed, 5 unresolved discussions (waiting on @eepp)

___
*[cli/babeltrace-cfg-cli-args.c, line 246 at r10](https://reviewable.io/reviews/eepp/babeltrace/30#-LdF0USjEzSBskMydwk9:-LdFPd6g4l1KRHv7OSX6:bsgsu6o) ([raw file](https://github.com/eepp/babeltrace/blob/b7dce1ef8d2716aedf54dacccf4cd68b15e06e23/cli/babeltrace-cfg-cli-args.c#L246)):*
<details><summary><i>Previously, eepp (Philippe Proulx) wrote…</i></summary><blockquote>

So you don't need any explicit `(uint64_t)` cast here?

I would have thought the compiler complains about a signed-unsigned comparison.
</blockquote></details>

For some reason no, even when I add `-Wsign-compare`.

I guess it's consistent with the fact that `some_unsigned_int < 10` doesn't warn either, which is perfectly fine.
___
*[plugins/ctf/fs-src/fs.c, line 1329 at r15](https://reviewable.io/reviews/eepp/babeltrace/30#-LdF6s-kB_VTyJRdwaBX:-LdFVQGP0PgvFp25fNIR:bx2klj7) ([raw file](https://github.com/eepp/babeltrace/blob/4f816d5bc133e395365062e1d3ea38d42cc62a6c/plugins/ctf/fs-src/fs.c#L1329)):*
<details><summary><i>Previously, eepp (Philippe Proulx) wrote…</i></summary><blockquote>

Minor: put `*/` below.
</blockquote></details>

I've adjusted all block comments in this patch.
___
*[plugins/ctf/fs-src/fs.c, line 1398 at r15](https://reviewable.io/reviews/eepp/babeltrace/30#-LdF7Nfx5LegLKFTruhp:-LdFVyVJECtluirftpnC:b-896fix) ([raw file](https://github.com/eepp/babeltrace/blob/4f816d5bc133e395365062e1d3ea38d42cc62a6c/plugins/ctf/fs-src/fs.c#L1398)):*
<details><summary><i>Previously, eepp (Philippe Proulx) wrote…</i></summary><blockquote>

Block comment style.
</blockquote></details>

Done.
___
*[plugins/ctf/fs-src/fs.c, line 1400 at r15](https://reviewable.io/reviews/eepp/babeltrace/30#-LdF7RMY4ncjHKZdMCiG:-LdFW6Er8eRs-yaBqgYr:b-896fix) ([raw file](https://github.com/eepp/babeltrace/blob/4f816d5bc133e395365062e1d3ea38d42cc62a6c/plugins/ctf/fs-src/fs.c#L1400)):*
<details><summary><i>Previously, eepp (Philippe Proulx) wrote…</i></summary><blockquote>

Indent this one one more time.
</blockquote></details>

Done.
___
*[plugins/ctf/fs-src/fs.c, line 1410 at r15](https://reviewable.io/reviews/eepp/babeltrace/30#-LdF7V10DPo_H9U4BNut:-LdFW8QQ0DS_dpKEL-pA:b-896fix) ([raw file](https://github.com/eepp/babeltrace/blob/4f816d5bc133e395365062e1d3ea38d42cc62a6c/plugins/ctf/fs-src/fs.c#L1410)):*
<details><summary><i>Previously, eepp (Philippe Proulx) wrote…</i></summary><blockquote>

Block comment style.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-04-24 21:17 UTC, eepp approved these changes
> Reviewed 34 of 34 files at r16, 4 of 4 files at r17, 1 of 1 files at r18, 5 of 5 files at r19, 27 of 27 files at r20, 35 of 35 files at r21, 1 of 1 files at r22, 1 of 1 files at r23, 2 of 2 files at r24, 4 of 4 files at r25, 1 of 1 files at r26, 5 of 5 files at r27, 1 of 1 files at r28.
> *[Reviewable](https://reviewable.io/reviews/eepp/babeltrace/30)* status: all files reviewed, 1 unresolved discussion (waiting on @simark)

___
*[cli/babeltrace-cfg-cli-args.c, line 246 at r10](https://reviewable.io/reviews/eepp/babeltrace/30#-LdF0USjEzSBskMydwk9:-LdG8EIaB_hPrI1eHjcR:b-l5ppee) ([raw file](https://github.com/eepp/babeltrace/blob/b7dce1ef8d2716aedf54dacccf4cd68b15e06e23/cli/babeltrace-cfg-cli-args.c#L246)):*
<details><summary><i>Previously, simark (Simon Marchi) wrote…</i></summary><blockquote>

For some reason no, even when I add `-Wsign-compare`.

I guess it's consistent with the fact that `some_unsigned_int < 10` doesn't warn either, which is perfectly fine.
</blockquote></details>

You know I'm the kind of freak who would prefer `some_unsigned_int < 10U`.


<!-- Sent from Reviewable.io -->

2019-04-24 21:20 UTC, simark commented
> You know I'm the kind of freak who would prefer `some_unsigned_int < 10U`.

Yes.

2019-04-24 21:22 UTC, eepp approved these changes
> *[Reviewable](https://reviewable.io/reviews/eepp/babeltrace/30)* status: all files reviewed, 1 unresolved discussion (waiting on @simark)



<!-- Sent from Reviewable.io -->

2019-04-24 21:22 UTC, eepp approved these changes
> *[Reviewable](https://reviewable.io/reviews/eepp/babeltrace/30)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2019-04-24 21:23 UTC, merged