Make the bt2 Python bindings build
eepp/babeltrace pull request #31
Opened 2019-04-22 15:43 UTC by simark

2019-04-22 15:46 UTC, simark commented
The goal of this PR is to reach the point where we can configure and build with `--enable-python-bindings`. It's probably still a bit rough (some little errors, stuff that may end up unused), but there are many more PRs to come to fix those.

2019-04-22 21:18 UTC, frdeso commented
*[a discussion](https://reviewable.io/reviews/eepp/babeltrace/31#-Ld5tyPcCmxeqmflfslE:-Ld5tyPdCMKW5gqfvHKC:b-hqws8s) (no related file):*
Should we include the commit to skip all the python tests as well?

---


<!-- Sent from Reviewable.io -->

2019-04-22 21:34 UTC, simark reviewed
> *[Reviewable](https://reviewable.io/reviews/eepp/babeltrace/31)* status: 0 of 49 files reviewed, 1 unresolved discussion (waiting on @frdeso)

*[a discussion](https://reviewable.io/reviews/eepp/babeltrace/31#-Ld5tyPcCmxeqmflfslE:-Ld5y6eS9JQopA8WwmvC:beuhj5j) (no related file):*
<details><summary><i>Previously, frdeso (Francis Deslauriers) wrote…</i></summary><blockquote>

Should we include the commit to skip all the python tests as well?
</blockquote></details>

That will come in a sequel to this PR!

---


<!-- Sent from Reviewable.io -->

2019-04-22 21:42 UTC, frdeso commented
*[a discussion](https://reviewable.io/reviews/eepp/babeltrace/31#-Ld5tyPcCmxeqmflfslE:-Ld5zuER3ytnh6rrVGCh:b-7vcmu2) (no related file):*
<details><summary><i>Previously, simark (Simon Marchi) wrote…</i></summary><blockquote>

That will come in a sequel to this PR!
</blockquote></details>

Can't wait!

---


<!-- Sent from Reviewable.io -->

2019-04-23 19:09 UTC, eepp requested changes
I don't know what is coming after this pull request, but I still commented the C parts in those SWIG interface files.

> Reviewed 49 of 49 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eepp/babeltrace/31#-:-LdAaPUM3fYW7hxfhI3G:b-j1phsc)* status: all files reviewed, 32 unresolved discussions (waiting on @simark)

___
*[bindings/python/bt2/bt2/native_bt.i, line 48 at r1](https://reviewable.io/reviews/eepp/babeltrace/31#-Ld6GxAO5OYh68z7q7oC:-Ld6GxAO5OYh68z7q7oD:b-w8kvh4) ([raw file](https://github.com/eepp/babeltrace/blob/50f5f85f14106b084a4e1870a5adbf4526949d49/bindings/python/bt2/bt2/native_bt.i#L48)):*
> ```
> %include "stdint.i"
> 
> /* Remove `bt_` and `BT_` prefixes from function names, global variables and
> ```

Coding style: block comment.
___
*[bindings/python/bt2/bt2/native_bt.i, line 190 at r1](https://reviewable.io/reviews/eepp/babeltrace/31#-Ld6HHt-07_RzQNW-nSC:-Ld6HHt-07_RzQNW-nSD:bv5gam3) ([raw file](https://github.com/eepp/babeltrace/blob/50f5f85f14106b084a4e1870a5adbf4526949d49/bindings/python/bt2/bt2/native_bt.i#L190)):*
> ```
> 		$result = SWIG_Python_AppendOutput($result,
> 				SWIG_NewPointerObj(SWIG_as_voidptr(*$1),
> 					SWIGTYPE_p_bt_field_class_unsigned_enumeration_mapping_ranges, 0));
> ```

I really hope those type names are part of the SWIG API...
___
*[bindings/python/bt2/bt2/native_bt_component_class.i, line 4 at r1](https://reviewable.io/reviews/eepp/babeltrace/31#-Ld6NufS4Si-dvusYdj4:-Ld6NufS4Si-dvusYdj5:b-3iuw1u) ([raw file](https://github.com/eepp/babeltrace/blob/50f5f85f14106b084a4e1870a5adbf4526949d49/bindings/python/bt2/bt2/native_bt_component_class.i#L4)):*
> ```
>  * The MIT License (MIT)
>  *
>  * Copyright (c) 2017 Philippe Proulx <pproulx@efficios.com>
> ```

Add yourself!
___
*[bindings/python/bt2/bt2/native_bt_component_class.i, line 605 at r1](https://reviewable.io/reviews/eepp/babeltrace/31#-Ld6M_jJ2z08QOB4UrhI:-Ld6M_jJ2z08QOB4UrhJ:bfcq0me) ([raw file](https://github.com/eepp/babeltrace/blob/50f5f85f14106b084a4e1870a5adbf4526949d49/bindings/python/bt2/bt2/native_bt_component_class.i#L605)):*
> ```
> // in a try catch and print the error there instead, it would be simpler.
> static void
> bt2_py_loge_exception()
> ```

Return type can be here (check other locations too).

Have `void` parameter.
___
*[bindings/python/bt2/bt2/native_bt_component_class.i, line 628 at r1](https://reviewable.io/reviews/eepp/babeltrace/31#-Ld6MyOsBHC1Lqk4y4IH:-Ld6MyOsBHC1Lqk4y4II:brarzdg) ([raw file](https://github.com/eepp/babeltrace/blob/50f5f85f14106b084a4e1870a5adbf4526949d49/bindings/python/bt2/bt2/native_bt_component_class.i#L628)):*
> ```
>      */
> 
>     PyErr_NormalizeException(&type, &value, &traceback);
> ```

Comment.
___
*[bindings/python/bt2/bt2/native_bt_component_class.i, line 632 at r1](https://reviewable.io/reviews/eepp/babeltrace/31#-Ld6N10d5TWHcdtrSq54:-Ld6N10d5TWHcdtrSq55:b76pyql) ([raw file](https://github.com/eepp/babeltrace/blob/50f5f85f14106b084a4e1870a5adbf4526949d49/bindings/python/bt2/bt2/native_bt_component_class.i#L632)):*
> ```
>     traceback_module = PyImport_ImportModule("traceback");
>     if (traceback_module == NULL) {
>         BT_LOGE("Failed to log Python exception (could not import traceback module).");
> ```

Use `BT_LOGE_STR()`. Below too when appropriate.
___
*[bindings/python/bt2/bt2/native_bt_component_class.i, line 657 at r1](https://reviewable.io/reviews/eepp/babeltrace/31#-Ld6NR_-44oXSwCSqSqW:-Ld6NR_-44oXSwCSqSqX:bd4gajm) ([raw file](https://github.com/eepp/babeltrace/blob/50f5f85f14106b084a4e1870a5adbf4526949d49/bindings/python/bt2/bt2/native_bt_component_class.i#L657)):*
> ```
>     msg_buf = g_string_new(NULL);
> 
>     for (int i = 0; i < PyList_Size(exc_str_list); i++) {
> ```

Declaration at the beginning.
___
*[bindings/python/bt2/bt2/native_bt_component_class.i, line 660 at r1](https://reviewable.io/reviews/eepp/babeltrace/31#-Ld6NXf843FG0hB6wuQQ:-Ld6NXf843FG0hB6wuQR:b5g24b6) ([raw file](https://github.com/eepp/babeltrace/blob/50f5f85f14106b084a4e1870a5adbf4526949d49/bindings/python/bt2/bt2/native_bt_component_class.i#L660)):*
> ```
>         PyObject *exc_str = PyList_GetItem(exc_str_list, i);
>         const char *str = PyUnicode_AsUTF8(exc_str);
>         if (str == NULL) {
> ```

`!str` (check other locations too).
___
*[bindings/python/bt2/bt2/native_bt_component_class.i, line 668 at r1](https://reviewable.io/reviews/eepp/babeltrace/31#-Ld6N_OO2LIvdOgo8Lh-:-Ld6N_OO2LIvdOgo8Lh0:bn61kl6) ([raw file](https://github.com/eepp/babeltrace/blob/50f5f85f14106b084a4e1870a5adbf4526949d49/bindings/python/bt2/bt2/native_bt_component_class.i#L668)):*
> ```
>     }
> 
>     BT_LOGE("%s", msg_buf->str);
> ```

`BT_LOGE_STR()`
___
*[bindings/python/bt2/bt2/native_bt_component_class.i, line 725 at r1](https://reviewable.io/reviews/eepp/babeltrace/31#-Ld6O2CN-s_r851GHc4q:-Ld6O2CN-s_r851GHc4r:b4vjg3c) ([raw file](https://github.com/eepp/babeltrace/blob/50f5f85f14106b084a4e1870a5adbf4526949d49/bindings/python/bt2/bt2/native_bt_component_class.i#L725)):*
> ```
> 	if (PyErr_GivenExceptionMatches(exc,
> 			py_mod_bt2_exc_unsupported_feature_type)) {
> 		// TODO: Is that right?
> ```

I don't think this exception will exist anymore after we fix the whole Python package.
___
*[bindings/python/bt2/bt2/native_bt_component_class.i, line 823 at r1](https://reviewable.io/reviews/eepp/babeltrace/31#-LdARgFGE4ta4mtIfHe6:-LdARgFGE4ta4mtIfHe7:bnh995s) ([raw file](https://github.com/eepp/babeltrace/blob/50f5f85f14106b084a4e1870a5adbf4526949d49/bindings/python/bt2/bt2/native_bt_component_class.i#L823)):*
> ```
> 			break;
> 	}
> 	BT_ASSERT(comp_cls_type_swig_type != NULL);
> ```

Often we just have a `default` case with `abort()`.
___
*[bindings/python/bt2/bt2/native_bt_component_class.i, line 824 at r1](https://reviewable.io/reviews/eepp/babeltrace/31#-LdARsBA8Nbw_us-m-GZ:-LdARsBA8Nbw_us-m-G_:b-2ka4qj) ([raw file](https://github.com/eepp/babeltrace/blob/50f5f85f14106b084a4e1870a5adbf4526949d49/bindings/python/bt2/bt2/native_bt_component_class.i#L824)):*
> ```
> 	}
> 	BT_ASSERT(comp_cls_type_swig_type != NULL);
> 	py_comp_ptr = SWIG_NewPointerObj(SWIG_as_voidptr(self_component),
> ```

From this function's point of view, how is this downcast safe?

I mean now you have a "SWIG pointer to a source self component", for example, but you don't have that initial address (conceptually).

I would prefer that this function receives a `void *` and a component class type, or a `void *` and a `bt_self_component *` (like currently, from which you can get the class type), and that the `void *` be casted to the appropriate self component type depending on the class type. Then you have, for example:

```c
static bt_self_component_status
bt_py3_component_class_source_init(bt_self_component_source *self_comp_src,
	const bt_value *params, void *init_method_data)
{
	return bt_py3_component_class_init(
		bt_self_component_source_as_self_component(self_component_source),
		self_comp_src, params, init_method_data);
}
```
___
*[bindings/python/bt2/bt2/native_bt_component_class.i, line 883 at r1](https://reviewable.io/reviews/eepp/babeltrace/31#-LdATGBP05SXgSLf6vcC:-LdATGBP05SXgSLf6vcD:bos0iop) ([raw file](https://github.com/eepp/babeltrace/blob/50f5f85f14106b084a4e1870a5adbf4526949d49/bindings/python/bt2/bt2/native_bt_component_class.i#L883)):*
> ```
> static bt_self_component_status
> bt_py3_component_class_source_init(bt_self_component_source *self_component_source,
> 		                           const bt_value *params, void *init_method_data)
> ```

We just use two tabs for line continuation, we don't align.
___
*[bindings/python/bt2/bt2/native_bt_component_class.i, line 886 at r1](https://reviewable.io/reviews/eepp/babeltrace/31#-LdAT2Lw4pPZ_2y6Tawq:-LdAT2Lw4pPZ_2y6Tawr:bvm9dg7) ([raw file](https://github.com/eepp/babeltrace/blob/50f5f85f14106b084a4e1870a5adbf4526949d49/bindings/python/bt2/bt2/native_bt_component_class.i#L886)):*
> ```
> {
> 	bt_self_component *self_component = bt_self_component_source_as_se [...]

2019-04-23 23:21 UTC, eepp requested changes
I don't know if this push was intended to be a new revision as there are still a few unaddressed blocking comments, but I reviewed what I could anyway and retracted the blocking comments where changes were done.

I really like that the SWIG interface file names are synced with the header file names now.

Could you investigate including the project's headers directly instead of copying them? I think that our headers are clean enough that this could work pretty well. It looks like SWIG will ignore `#include` directives in an interface, so this is good, because it means we don't care about header files including other header files. So the `native_bt_value.i` file could look like this for example:

```
%include "babeltrace/trace-ir/clock-class-const.h"
%include "babeltrace/trace-ir/clock-class.h"
```

We need to pass the appropriate `-I` option to SWIG for it to search into the `include` directory.

We could have issues with typemaps, but since most of them (if not all) work by type instead of by name now, it should work.

Another downside is that everything is included in the interface file and therefore gets translated into a Python module, but since we're wrapping this Python module with our own package anyway, we don't care if there's some extra stuff in there. Plus the intention is to wrap the whole C API, so not much will be superfluous.

What do you think?

> Reviewed 1 of 47 files at r2, 47 of 47 files at r3.
> *[Reviewable](https://reviewable.io/reviews/eepp/babeltrace/31#-:-LdBRL74292f23rCIRr5:b-fjx0o1)* status: all files reviewed, 25 unresolved discussions (waiting on @simark)

___
*[bindings/python/bt2/bt2/native_bt.i, line 90 at r3](https://reviewable.io/reviews/eepp/babeltrace/31#-LdBMLbsDAyIaB3sgFPA:-LdBMLbsDAyIaB3sgFPB:bg0d05) ([raw file](https://github.com/eepp/babeltrace/blob/e6813f12365e070d4f182faa8107ff3c1f0c4d45/bindings/python/bt2/bt2/native_bt.i#L90)):*
> ```
> 
> /* Output argument typemap for initialized uint64_t output parameter (always appends) */
> %typemap(in, numinputs=0) (uint64_t *OUTPUTINT) (uint64_t temp = -1ULL) {
> ```

Any reason this is named `OUTPUTINT` while other ones have the form `OUT_*`?
___
*[bindings/python/bt2/bt2/native_bt_component_class.i, line 713 at r3](https://reviewable.io/reviews/eepp/babeltrace/31#-LdBNfveB5nd28OB4jiV:-LdBNfveB5nd28OB4jiW:b6zrrkh) ([raw file](https://github.com/eepp/babeltrace/blob/e6813f12365e070d4f182faa8107ff3c1f0c4d45/bindings/python/bt2/bt2/native_bt_component_class.i#L713)):*
> ```
> bt_py3_exc_to_self_message_iterator_status(void)
> {
> 	enum bt_self_message_iterator_status status =
> ```

Good catch.
___
*[bindings/python/bt2/bt2/native_bt_component_class.i, line 767 at r3](https://reviewable.io/reviews/eepp/babeltrace/31#-LdBO9om4SKH6uMPvoUh:-LdBO9om4SKH6uMPvoUi:bm315j2) ([raw file](https://github.com/eepp/babeltrace/blob/e6813f12365e070d4f182faa8107ff3c1f0c4d45/bindings/python/bt2/bt2/native_bt_component_class.i#L767)):*
> ```
> 		bt_self_component *self_component,
> 		void *self_component_v,
> 		swig_type_info *self_comp_cls_type_swig_type,
> ```

Yes this is also a good alternative.
___
*[bindings/python/bt2/bt2/native_bt_event_class.i, line 34 at r3](https://reviewable.io/reviews/eepp/babeltrace/31#-LdBP8jX8mmQE9iXjxWe:-LdBP8jX8mmQE9iXjxWf:b-b9erfa) ([raw file](https://github.com/eepp/babeltrace/blob/e6813f12365e070d4f182faa8107ff3c1f0c4d45/bindings/python/bt2/bt2/native_bt_event_class.i#L34)):*
> ```
> }
> 
> %typemap(argout) bt_event_class_log_level *OUT_INIT_EC_LOG_LEVEL {
> ```

`INIT`?
___
*[bindings/python/bt2/bt2/native_bt_field_class.i, line 26 at r3](https://reviewable.io/reviews/eepp/babeltrace/31#-LdBPINi3fho-SIBOOD8:-LdBPINj5V8Ioyhpt7lO:bnjhmes) ([raw file](https://github.com/eepp/babeltrace/blob/e6813f12365e070d4f182faa8107ff3c1f0c4d45/bindings/python/bt2/bt2/native_bt_field_class.i#L26)):*
> ```
> 
> %typemap(in, numinputs=0)
> 	(bt_field_class_enumeration_mapping_label_array *LABELARRAY, uint64_t *LABELCOUNT)
> ```

Should those be prefixed with `OUT_` also?
___
*[bindings/python/bt2/bt2/native_bt_field_class.i, line 49 at r3](https://reviewable.io/reviews/eepp/babeltrace/31#-LdBPNoz2z4rj6OvbLov:-LdBPNoz2z4rj6OvbLow:b-8b37w5) ([raw file](https://github.com/eepp/babeltrace/blob/e6813f12365e070d4f182faa8107ff3c1f0c4d45/bindings/python/bt2/bt2/native_bt_field_class.i#L49)):*
> ```
> /* Output argument typemap for value output (always appends) */
> %typemap(in, numinputs=0)
> 	(const bt_field_class_signed_enumeration_mapping_ranges **ENUM_RANGE_MAPPING)
> ```

`OUT_`?
___
*[bindings/python/bt2/bt2/native_bt_graph.i, line 27 at r3](https://reviewable.io/reviews/eepp/babeltrace/31#-LdBPZHA0ls4qpxUhg-w:-LdBPZHA0ls4qpxUhg-x:bd1nltw) ([raw file](https://github.com/eepp/babeltrace/blob/e6813f12365e070d4f182faa8107ff3c1f0c4d45/bindings/python/bt2/bt2/native_bt_graph.i#L27)):*
> ```
> /* Output argument typemap for connection output (always appends) */
> %typemap(in, numinputs=0)
> 	(const bt_connection **BTOUTCONN)
> ```

For all the typemap names below, use the `OUT_` format?
___
*[bindings/python/bt2/bt2/native_bt_message.i, line 28 at r3](https://reviewable.io/reviews/eepp/babeltrace/31#-LdBPtol3nxuwrWG8vSW:-LdBPtol3nxuwrWG8vSX:blcbgzj) ([raw file](https://github.com/eepp/babeltrace/blob/e6813f12365e070d4f182faa8107ff3c1f0c4d45/bindings/python/bt2/bt2/native_bt_message.i#L28)):*
> ```
> /* Output argument typemap for clock value output (always appends) */
> %typemap(in, numinputs=0)
> 	(const bt_clock_snapshot **BTOUTCLOCKSNAPSHOT)
> ```

`OUT_` name format?
___
*[bindings/python/bt2/bt2/native_bt_trace.i, line 100 at r3](https://reviewable.io/reviews/eepp/babeltrace/31#-LdBQ6ll95QiIkW8wlza:-LdBQ6ll95QiIkW8wlzb:b4mvff) ([raw file](https://github.com/eepp/babeltrace/blob/e6813f12365e070d4f182faa8107ff3c1f0c4d45/bindings/python/bt2/bt2/native_bt_trace.i#L100)):*
> ```
> }
> 
> uint64_t bt_py3_trace_add_destruction_listener(bt_trace *trace,	PyObject *py_callable)
> ```

Weird tab here.
___
*[bindings/python/bt2/bt2/native_bt_trace.i, line 102 at r3](https://reviewable.io/reviews/eepp/babeltrace/31#-LdBQoA9D0FsrFvU_V5k:-LdBQoA9D0FsrFvU_V5l:b5jpa3g) ([raw file](https://github.com/eepp/babeltrace/blob/e6813f12365e070d4f182faa8107ff3c1f0c4d45/bindings/python/bt2/bt2/native_bt_trace.i#L102)):*
> ```
> uint64_t bt_py3_trace_add_destruction_listener(bt_trace *trace,	PyObject *py_callable)
> {
> 	uint64_t id = (uint64_t) -1;
> ```

I use `UINT64_C(-1)` now.
___
*[bindings/python/bt2/bt2/native_bt_trace.i, line 107 at r3](https://reviewable.io/reviews/eepp/babeltrace/31#-LdBQB3xAuQSg8_RxXf0:-LdBQB3xAuQSg8_RxXf1:b-pt89wu) ([raw file](https://github.com/eepp/babeltrace/blob/e6813f12365e070d4f182faa8107ff3c1f0c4d45/bindings/python/bt2/bt2/native_bt_trace.i#L107)):*
> ```
> 	BT_ASSERT(py_callable);
> 
> 	bt_trace_status status = bt_trace_add_destruction_listener(
> ```

Declare at the beginning.
___
*[bindings/python/bt2/bt2/native_bt_trace.i, line 111 at r3](https://reviewable.io/reviews/eepp/babeltrace/31#-LdBQEI6DbYUcuF2STVd:-LdBQEI6DbYUcuF2STVe:br04y8s) ([raw file](https://github.com/eepp/babeltrace/blob/e6813f12365e070d4f182faa8107ff3c1f0c4d45/bindings/python/bt2/bt2/native_bt_trace.i#L111)):*
> ```
> 	if (status != BT_TRACE_STATUS_OK) {
> 		// TODO: Raise a Python exception?
> 		BT_LOGF_STR("Failed to add trace destruction listener.");
> ```

`BT_LOGF()` is usually followed by `abort()`.

The only reason this could fail is no memory, so it's probably okay to just abort. I wouldn't know what to raise.
___
*[bindings/python/bt2/bt2/native_bt_trace_class.i, line 142 at r3](https://reviewable.io/reviews/eepp/babeltrace/31#-LdBQxhaDA2xzI2sq-Ap:-LdBQxhaDA2xzI2sq-Aq:b-69h686) ([raw file](https://github.com/eepp/babeltrace/blob/e6813f12365e070d4f182faa8107ff3c1f0c4d45/bindings/python/bt2/bt2/native_bt_trace_class.i#L142)):*
> ```
> 	if (status != BT_TRACE_CLASS_STATUS_OK) {
> 		// TODO: Raise a Python exception?
> 		BT_LOGF_STR("Failed to add trace class destruction listener.") [...]

2019-04-24 13:40 UTC, simark reviewed
> I don't know if this push was intended to be a new revision as there are still a few unaddressed blocking comments, but I reviewed what I could anyway and retracted the blocking comments where changes were done.

It was intended, but as I said on IRC :)

```
simark: Je suis à ~80% de passer sur les review comments pour "Make Python buildable again"                                                                                                           
simark: Une fois que j'ai fini, il va falloir que je fasse un petit smoke test, rebaser optimalize-python-split dessus voir si tout passe encore                                                    │
simark: je vais finir ça demain                                                                                                                                                                     simark: j'ai poussé sur ma branche pour pas perdre mon travail dans l'éventualité ou mon laptop se pitche en bas de la fenêtre                                                                      │
simark: ça a créé un r3, mais tu peux le disregarder  
```

> I really like that the SWIG interface file names are synced with the header file names now.
> 
> Could you investigate including the project's headers directly instead of copying them? I think that our headers are clean enough that this could work pretty well. It looks like SWIG will ignore #include directives in an interface, so this is good, because it means we don't care about header files including other header files. So the native_bt_value.i file could look like this for example:
> 
> %include "babeltrace/trace-ir/clock-class-const.h"
> %include "babeltrace/trace-ir/clock-class.h"
> We need to pass the appropriate -I option to SWIG for it to search into the include directory.
> 
> We could have issues with typemaps, but since most of them (if not all) work by type instead of by name now, it should work.
> 
> Another downside is that everything is included in the interface file and therefore gets translated into a Python module, but since we're wrapping this Python module with our own package anyway, we don't care if there's some extra stuff in there. Plus the intention is to wrap the whole C API, so not much will be superfluous.
> 
> What do you think?

Yes, I thought about that too, and it was my plan to try it eventually (but first, merging with the current strategy of copying the declarations, since we already have it and we know it works well).

I have addressed most comments (all except two that will take a bit more time, I left them pending). I will push a new revision, r4 (to keep my branch up to date), but you don't have to look at it.

> *[Reviewable](https://reviewable.io/reviews/eepp/babeltrace/31#-:-LdENnjXEHcZH_rcvhb8:bjkq8dd)* status: all files reviewed, 21 unresolved discussions (waiting on @eepp, @frdeso, and @simark)

*[a discussion](https://reviewable.io/reviews/eepp/babeltrace/31#-Ld5tyPcCmxeqmflfslE:-LdAg3QP48JUBLwyfmvS:b-896fix) (no related file):*
<details><summary><i>Previously, frdeso (Francis Deslauriers) wrote…</i></summary><blockquote>

Can't wait!
</blockquote></details>

Done.

---
___
*[bindings/python/bt2/bt2/native_bt.i, line 48 at r1](https://reviewable.io/reviews/eepp/babeltrace/31#-Ld6GxAO5OYh68z7q7oC:-LdAgQqy6kSubAXezK2h:b-896fix) ([raw file](https://github.com/eepp/babeltrace/blob/50f5f85f14106b084a4e1870a5adbf4526949d49/bindings/python/bt2/bt2/native_bt.i#L48)):*
<details><summary><i>Previously, eepp (Philippe Proulx) wrote…</i></summary><blockquote>

Coding style: block comment.
</blockquote></details>

Done.
___
*[bindings/python/bt2/bt2/native_bt.i, line 90 at r3](https://reviewable.io/reviews/eepp/babeltrace/31#-LdBMLbsDAyIaB3sgFPA:-LdEN34L2G4FCKJndUud:b-3p3q4k) ([raw file](https://github.com/eepp/babeltrace/blob/e6813f12365e070d4f182faa8107ff3c1f0c4d45/bindings/python/bt2/bt2/native_bt.i#L90)):*
<details><summary><i>Previously, eepp (Philippe Proulx) wrote…</i></summary><blockquote>

Any reason this is named `OUTPUTINT` while other ones have the form `OUT_*`?
</blockquote></details>

Probably not.  As I said, I would try to name all of them `OUT`.
___
*[bindings/python/bt2/bt2/native_bt_component_class.i, line 4 at r1](https://reviewable.io/reviews/eepp/babeltrace/31#-Ld6NufS4Si-dvusYdj4:-LdAgSeUBPitZb976fVv:b-e91vl7) ([raw file](https://github.com/eepp/babeltrace/blob/50f5f85f14106b084a4e1870a5adbf4526949d49/bindings/python/bt2/bt2/native_bt_component_class.i#L4)):*
<details><summary><i>Previously, eepp (Philippe Proulx) wrote…</i></summary><blockquote>

Add yourself!
</blockquote></details>

I'd be fine if we just put "EfficiOS", so we wouldn't have to change it again :).
___
*[bindings/python/bt2/bt2/native_bt_component_class.i, line 605 at r1](https://reviewable.io/reviews/eepp/babeltrace/31#-Ld6M_jJ2z08QOB4UrhI:-LdAgouyCmEffSDt7L8N:b-896fix) ([raw file](https://github.com/eepp/babeltrace/blob/50f5f85f14106b084a4e1870a5adbf4526949d49/bindings/python/bt2/bt2/native_bt_component_class.i#L605)):*
<details><summary><i>Previously, eepp (Philippe Proulx) wrote…</i></summary><blockquote>

Return type can be here (check other locations too).

Have `void` parameter.
</blockquote></details>

Done.
___
*[bindings/python/bt2/bt2/native_bt_component_class.i, line 628 at r1](https://reviewable.io/reviews/eepp/babeltrace/31#-Ld6MyOsBHC1Lqk4y4IH:-LdAhPWeBWWVBSUpwVhZ:b-896fix) ([raw file](https://github.com/eepp/babeltrace/blob/50f5f85f14106b084a4e1870a5adbf4526949d49/bindings/python/bt2/bt2/native_bt_component_class.i#L628)):*
<details><summary><i>Previously, eepp (Philippe Proulx) wrote…</i></summary><blockquote>

Comment.
</blockquote></details>

Done.
___
*[bindings/python/bt2/bt2/native_bt_component_class.i, line 632 at r1](https://reviewable.io/reviews/eepp/babeltrace/31#-Ld6N10d5TWHcdtrSq54:-LdAhec-AcNDlvlb90gi:bne7b2s) ([raw file](https://github.com/eepp/babeltrace/blob/50f5f85f14106b084a4e1870a5adbf4526949d49/bindings/python/bt2/bt2/native_bt_component_class.i#L632)):*
<details><summary><i>Previously, eepp (Philippe Proulx) wrote…</i></summary><blockquote>

Use `BT_LOGE_STR()`. Below too when appropriate.
</blockquote></details>

Done, but what's the issue with `BT_LOGE`?  It would be like doing `printf("Hello\n")`, I don't see the problem.
___
*[bindings/python/bt2/bt2/native_bt_component_class.i, line 657 at r1](https://reviewable.io/reviews/eepp/babeltrace/31#-Ld6NR_-44oXSwCSqSqW:-LdAjafxBcKpd_73LIqd:b-896fix) ([raw file](https://github.com/eepp/babeltrace/blob/50f5f85f14106b084a4e1870a5adbf4526949d49/bindings/python/bt2/bt2/native_bt_component_class.i#L657)):*
<details><summary><i>Previously, eepp (Philippe Proulx) wrote…</i></summary><blockquote>

Declaration at the beginning.
</blockquote></details>

Done.
___
*[bindings/python/bt2/bt2/native_bt_component_class.i, line 660 at r1](https://reviewable.io/reviews/eepp/babeltrace/31#-Ld6NXf843FG0hB6wuQQ:-LdAjvP49gVz2Z6Zs0WQ:b-896fix) ([raw file](https://github.com/eepp/babeltrace/blob/50f5f85f14106b084a4e1870a5adbf4526949d49/bindings/python/bt2/bt2/native_bt_component_class.i#L660)):*
<details><summary><i>Previously, eepp (Philippe Proulx) wrote…</i></summary><blockquote>

`!str` (check other locations too).
</blockquote></details>

Done.
___
*[bindings/python/bt2/bt2/native_bt_component_class.i, line 668 at r1](https://reviewable.io/reviews/eepp/babeltrace/31#-Ld6N_OO2LIvdOgo8Lh-:-LdAkFQpEJJAgNsII2S2:b-896fix) ([raw file](https://github.com/eepp/babeltrace/blob/50f5f85f14106b084a4e1870a5adbf4526949d49/bindings/python/bt2/bt2/native_bt_component_class.i#L668)):*
<details><summary><i>Previously, eepp (Philippe Proulx) wrote…</i></summary><blockquote>

`BT_LOGE_STR()`
</blockquote></details>

Done.
___
*[bindings/python/bt2/bt2/native_bt_component_class.i, line 725 at r1](https://reviewable.io/reviews/eepp/babeltrace/31#-Ld6O2CN-s_r851GHc4q:-LdAla8Z2b1cGtXsPE2S:b9dsvn2) ([raw file](https://github.com/eepp/babeltrace/blob/50f5f85f14106b084a4e1870a5adbf4526949d49/bi [...]

2019-04-24 16:41 UTC, eepp requested changes
> I have addressed most comments (all except two that will take a bit more time, I left them pending). I will push a new revision, r4 (to keep my branch up to date), but you don't have to look at it.

Damn, I looked at it before reading this. But the only blocking comments left are about SWIG typemap naming and I understood you'll fix it in r5.

> Reviewed 13 of 13 files at r4.
> *[Reviewable](https://reviewable.io/reviews/eepp/babeltrace/31#-:-LdFCjFICOssPSX1p_dT:b-xtvy2a)* status: all files reviewed, 8 unresolved discussions (waiting on @eepp, @frdeso, and @simark)

___
*[bindings/python/bt2/bt2/native_bt_component_class.i, line 632 at r1](https://reviewable.io/reviews/eepp/babeltrace/31#-Ld6N10d5TWHcdtrSq54:-LdFAZmh0V7-Uymh5psT:bma1q28) ([raw file](https://github.com/eepp/babeltrace/blob/50f5f85f14106b084a4e1870a5adbf4526949d49/bindings/python/bt2/bt2/native_bt_component_class.i#L632)):*
<details><summary><i>Previously, simark (Simon Marchi) wrote…</i></summary><blockquote>

Done, but what's the issue with `BT_LOGE`?  It would be like doing `printf("Hello\n")`, I don't see the problem.
</blockquote></details>

Not a really important issue, but I would also use `puts()` instead of `printf()` for this use case. There's the (low) risk of having a literal conversion specifier introduced there eventually.

No strong opinion on my side, just a personal taste really.
___
*[bindings/python/bt2/bt2/native_bt_component_class.i, line 824 at r1](https://reviewable.io/reviews/eepp/babeltrace/31#-LdARsBA8Nbw_us-m-GZ:-LdFBhPzB9IHXJH4Oj3b:buojsyx) ([raw file](https://github.com/eepp/babeltrace/blob/50f5f85f14106b084a4e1870a5adbf4526949d49/bindings/python/bt2/bt2/native_bt_component_class.i#L824)):*
<details><summary><i>Previously, simark (Simon Marchi) wrote…</i></summary><blockquote>

Done.  I also passed the SWIG type as a parameter to get rid of the switch in `bt_py3_component_class_init`.

I see it as: the typed value `bt_self_component_source *self_comp_src` decays into an untyped value (the `void *`) and a type on the side (the `swig_type_info *`), but no info is lost in that process, it's just split in two.
</blockquote></details>

Exactly. 👍
___
*[bindings/python/bt2/bt2/native_bt_component_class.i, line 669 at r4](https://reviewable.io/reviews/eepp/babeltrace/31#-LdFBSIn1Rg2nu3d70ac:-LdFBSIn1Rg2nu3d70ad:b-9vm6xg) ([raw file](https://github.com/eepp/babeltrace/blob/144e8954d2e706e2482333d2ab1fccac7dd47f8d/bindings/python/bt2/bt2/native_bt_component_class.i#L669)):*
> ```
> 
> end:
> 	if (msg_buf != NULL) {
> ```

`if (msg_buf)`


<!-- Sent from Reviewable.io -->

2019-04-25 18:50 UTC, simark reviewed
> *[Reviewable](https://reviewable.io/reviews/eepp/babeltrace/31)* status: all files reviewed, 8 unresolved discussions (waiting on @eepp and @frdeso)

___
*[bindings/python/bt2/bt2/native_bt_component_class.i, line 669 at r4](https://reviewable.io/reviews/eepp/babeltrace/31#-LdFBSIn1Rg2nu3d70ac:-LdKjRj16MnUGUv_2OJm:b-896fix) ([raw file](https://github.com/eepp/babeltrace/blob/144e8954d2e706e2482333d2ab1fccac7dd47f8d/bindings/python/bt2/bt2/native_bt_component_class.i#L669)):*
<details><summary><i>Previously, eepp (Philippe Proulx) wrote…</i></summary><blockquote>

`if (msg_buf)`
</blockquote></details>

Done.
___
*[bindings/python/bt2/bt2/native_bt_graph.i, line 407 at r1](https://reviewable.io/reviews/eepp/babeltrace/31#-LdAZZIJAHAxOM16K5vJ:-LdKjqof9BwtYdLOxlVv:bvxzgg) ([raw file](https://github.com/eepp/babeltrace/blob/50f5f85f14106b084a4e1870a5adbf4526949d49/bindings/python/bt2/bt2/native_bt_graph.i#L407)):*
<details><summary><i>Previously, eepp (Philippe Proulx) wrote…</i></summary><blockquote>

How would the eventual Python code have access to the port components with only the port objects?
</blockquote></details>

Hmm I'll check, I guess in our tests we don't use it.  Is that the thing for which we said: a port parameter will always be provided with a component parameter (its owner), and therefore we won't need the `port.component` property, which would have required an ugly downcast?

We will need to pass the component and enhance the test to check it.
___
*[bindings/python/bt2/bt2/native_bt_notifier.i, line 231 at r1](https://reviewable.io/reviews/eepp/babeltrace/31#-LdA_NaOD7R4l-T1wwVs:-LdKp54j5bFv8vBU7Po8:b-xstq3r) ([raw file](https://github.com/eepp/babeltrace/blob/50f5f85f14106b084a4e1870a5adbf4526949d49/bindings/python/bt2/bt2/native_bt_notifier.i#L231)):*
<details><summary><i>Previously, eepp (Philippe Proulx) wrote…</i></summary><blockquote>

Could you factor out pretty much all of this code for both functions and accept a callback of the type:

    bt_message_iterator_status (*next_cb)(void *iter, bt_message_array_const *msgs, uint64_t *count);
</blockquote></details>

Instead of a callback, I just merged the common parts (after the `_iterator _next` calls) in a helper function that both functions call.  It's a bit less boilerplate.


<!-- Sent from Reviewable.io -->

2019-04-25 19:10 UTC, eepp requested changes
> Reviewed 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/eepp/babeltrace/31)* status: all files reviewed, 2 unresolved discussions (waiting on @frdeso and @simark)

___
*[bindings/python/bt2/bt2/native_bt_graph.i, line 407 at r1](https://reviewable.io/reviews/eepp/babeltrace/31#-LdAZZIJAHAxOM16K5vJ:-LdKq_Fh1uvkKGUgNqCU:btn0xtr) ([raw file](https://github.com/eepp/babeltrace/blob/50f5f85f14106b084a4e1870a5adbf4526949d49/bindings/python/bt2/bt2/native_bt_graph.i#L407)):*
<details><summary><i>Previously, simark (Simon Marchi) wrote…</i></summary><blockquote>

Hmm I'll check, I guess in our tests we don't use it.  Is that the thing for which we said: a port parameter will always be provided with a component parameter (its owner), and therefore we won't need the `port.component` property, which would have required an ugly downcast?

We will need to pass the component and enhance the test to check it.
</blockquote></details>

Exactly.

I mean the C callback gets the corresponding components, but the Python equivalent must also have access to them using `port.component`. Since you have the correct component types here, you don't need any downcast. Your `void *` + SWIG type pattern will work fine.


<!-- Sent from Reviewable.io -->

2019-04-25 19:29 UTC, simark reviewed
> *[Reviewable](https://reviewable.io/reviews/eepp/babeltrace/31)* status: all files reviewed, 2 unresolved discussions (waiting on @eepp and @frdeso)

___
*[bindings/python/bt2/bt2/native_bt_graph.i, line 407 at r1](https://reviewable.io/reviews/eepp/babeltrace/31#-LdAZZIJAHAxOM16K5vJ:-LdKxUyP2EHD3M7DOrXQ:b2ivvnz) ([raw file](https://github.com/eepp/babeltrace/blob/50f5f85f14106b084a4e1870a5adbf4526949d49/bindings/python/bt2/bt2/native_bt_graph.i#L407)):*
<details><summary><i>Previously, eepp (Philippe Proulx) wrote…</i></summary><blockquote>

Exactly.

I mean the C callback gets the corresponding components, but the Python equivalent must also have access to them using `port.component`. Since you have the correct component types here, you don't need any downcast. Your `void *` + SWIG type pattern will work fine.
</blockquote></details>

Actually, my thought was that we would remove `port.component` completely (and maybe even the C function `bt_port_borrow_component_const`?), and instead the component that owns the port would just always be passed along as a parameter on the side.  For example, in this callback (when you commented), we receive the components that own both ports, and they have the right types (`bt_component_source` and `bt_component_filter`).  Using `bt_component_borrow_component_const` is not as good, since it returns a more generic `bt_component`.


<!-- Sent from Reviewable.io -->

2019-04-25 19:37 UTC, eepp commented
___
*[bindings/python/bt2/bt2/native_bt_graph.i, line 407 at r1](https://reviewable.io/reviews/eepp/babeltrace/31#-LdAZZIJAHAxOM16K5vJ:-LdKymo519etXfMLzCEK:b-5lbwwq) ([raw file](https://github.com/eepp/babeltrace/blob/50f5f85f14106b084a4e1870a5adbf4526949d49/bindings/python/bt2/bt2/native_bt_graph.i#L407)):*
Yes, on the C API side you're right. But I don't see those components being passed to the Python side here: you're calling:

    ports_connected_listener(upstream_port, downstream_port, py_callable);

Then, above, you do:

> ```
> 	py_downstream_port_ptr = SWIG_NewPointerObj(
> 		SWIG_as_voidptr(downstream_port), SWIGTYPE_p_bt_port_input, 0);
> ```

This creates a Python input port wrapper, but AFAIK there's no way for the Python callable to access the original source/filter/sink component wrappers?


<!-- Sent from Reviewable.io -->

2019-04-25 19:40 UTC, simark reviewed
> *[Reviewable](https://reviewable.io/reviews/eepp/babeltrace/31)* status: all files reviewed, 2 unresolved discussions (waiting on @eepp and @frdeso)

___
*[bindings/python/bt2/bt2/native_bt_graph.i, line 407 at r1](https://reviewable.io/reviews/eepp/babeltrace/31#-LdAZZIJAHAxOM16K5vJ:-LdL-Sxe8aQFjIRgF1KD:bbn7ri3) ([raw file](https://github.com/eepp/babeltrace/blob/50f5f85f14106b084a4e1870a5adbf4526949d49/bindings/python/bt2/bt2/native_bt_graph.i#L407)):*
<details><summary><i>Previously, eepp (Philippe Proulx) wrote…</i></summary><blockquote>

Yes, on the C API side you're right. But I don't see those components being passed to the Python side here: you're calling:

    ports_connected_listener(upstream_port, downstream_port, py_callable);

Then, above, you do:

> ```
> 	py_downstream_port_ptr = SWIG_NewPointerObj(
> 		SWIG_as_voidptr(downstream_port), SWIGTYPE_p_bt_port_input, 0);
> ```

This creates a Python input port wrapper, but AFAIK there's no way for the Python callable to access the original source/filter/sink component wrappers?
</blockquote></details>

That's right, I acknowledge that this is a deficiency in the proposed code.  It shall be fixed at a later time.  Hopefully, as a subsequent revision of the current patch.  However, it is a bit difficult for me to make this change and test it right away.


<!-- Sent from Reviewable.io -->

2019-04-25 19:42 UTC, eepp commented
___
*[bindings/python/bt2/bt2/native_bt_graph.i, line 407 at r1](https://reviewable.io/reviews/eepp/babeltrace/31#-LdAZZIJAHAxOM16K5vJ:-LdL0CCMEQHBau3yo3Ph:buvfvm8) ([raw file](https://github.com/eepp/babeltrace/blob/50f5f85f14106b084a4e1870a5adbf4526949d49/bindings/python/bt2/bt2/native_bt_graph.i#L407)):*
<details><summary><i>Previously, simark (Simon Marchi) wrote…</i></summary><blockquote>

That's right, I acknowledge that this is a deficiency in the proposed code.  It shall be fixed at a later time.  Hopefully, as a subsequent revision of the current patch.  However, it is a bit difficult for me to make this change and test it right away.
</blockquote></details>

Ok I can merge this as it builds and it's the PR's only goal, and then I'll review again within another patch.


<!-- Sent from Reviewable.io -->

2019-04-25 19:46 UTC, eepp approved these changes

2019-04-25 19:46 UTC, eepp commented
Closing this. Can you submit the same patches to Gerrit so that I merge through it?

2019-04-25 19:46 UTC, closed without merging

2019-04-25 19:49 UTC, simark commented
You can also just push it manually to both your github and gerrit remotes (keeping them in sync).